### ISSUE TITLE
How to check if cache is actually operational?

### ISSUE THREAD

**Issue by FastNinja** [renefloor/flutter_cached_network_image#10]
I need to verify that app actually using cache when it is supposed to use cache instead of downloading the file.

I am not sure how exactly do that? 
Options:
- some kind of debugInfo might be helpful that can be switched on or off?
- Callback  (crazy idea):
```
   image: new CachedNetworkImageProvider(imageUrl, 
              onImageProvided: (imageFile, fromCache) => 
                  { /*
                       here developers can do something with file, or log, or alternate for how long it 
 should stay etc...
                    */
                    } ),
```

but basically I want to see somewhere:
```
 loaded from from URL 'www.site.com/file.png',
 used file from cache 'www.site.com/file.png',
...
...
used file from cache 'www.site.com/file.png',
```

**Comment by renefloor** [comment]
Yes options for loging would be a good idea. The callback is more work and kind of a breaking change. Do you see much use for that?

I guess I will add some debug logging with the option to turn it on or off.

**Comment by FastNinja** [comment]
logs are enough for sure!

**Comment by renefloor** [comment]
For issue #8 I was already building some logging, so will add that in a next release.

**Comment by renefloor** [comment]
Added in the [Cache Manager](https://github.com/renefloor/flutter_cache_manager/commit/1b880df53929e1b5de05e3e2b86456de8495fd62) so this will be added in the next release.
