### ISSUE TITLE
Possibility to cache s3 images

### ISSUE THREAD

**Issue by MallorcaSoftware** [renefloor/flutter_cached_network_image#103]
It is possible to cache s3 images?

**Comment by yizems** [comment]
I also found it, but I don't know how to modify it.

**Comment by calebisstupid** [comment]
S3 works with public images. However, if they are private/permission locked, it will not cache via URL alone because it will provide a unique signed URL each time. To get around this, we build a re-direct endpoint on the back-end so our images can use the same URL for caching appropriately.

**Comment by renefloor** [comment]
Can be done with a custom FileFetcher, but if you have any suggestions how you would like to see this implemented I am open for suggestions.

**Comment by alexislg2** [comment]
Isn't it possible to tell the plugin to only use the url without the query parameters?
