### ISSUE TITLE
Saved data of non-image type？

### ISSUE THREAD

**Issue by wuchaofan** [renefloor/flutter_cached_network_image#106]
![image](https://user-images.githubusercontent.com/2271403/49988873-5d0a8700-ffb3-11e8-953a-0e7354f7652c.png)
[flutter_cache_manager code](https://github.com/renefloor/flutter_cache_manager/blob/master/lib/flutter_cache_manager.dart#L279)

Resulting in an error：
[cached_network_image code](https://github.com/renefloor/flutter_cached_network_image/blob/master/lib/cached_network_image.dart#L487)
![image](https://user-images.githubusercontent.com/2271403/49988972-af4ba800-ffb3-11e8-88cb-63b6662c716f.png)

bytes.lengthInBytes Always greater than 0

can set a flag to just save the image?

**Comment by renefloor** [comment]
Not sure what you want. Do you know beforehand that it is not an image? In that case, why use CachedNetworkImage? You can also use the CacheManager directly. Or should it be an image but you get a wrong result?
