### ISSUE TITLE
No animation while already in cache

### ISSUE THREAD

**Issue by neckaros** [renefloor/flutter_cached_network_image#108]
Hello, 
Is there a way to not show the animation/placeholder and directly the image if the image is already in cache?

**Comment by renefloor** [comment]
Currently not. Good idea though

**Comment by renefloor** [comment]
@neckaros The new version (v0.6.0) is much quicker in showing cached images. It still shows the placeholder first, but doesn't do an API call to check the validity of the image first. When the image is already shown once and is in memory it doesn't show the placeholder at all anymore
