### ISSUE TITLE
Image loaded from cache does not redraw

### ISSUE THREAD

**Issue by mshipton** [renefloor/flutter_cached_network_image#11]
I'm using `CachedNetworkImageProvider` to populate `Image` cells inside a `SliverGrid` from a list of image urls.

Given two lists of image urls [A, B, C], [D, E, F]:

* I show the first list. All images load correctly and appear on screen.
* I toggle the second list. All images load correctly and appear on screen.

**Comment by renefloor** [comment]
I don't really understand what you are trying to achieve and what goes wrong. Does the second list show images from the first list?

Can you give a code example and show what doesn't work as expected?

**Comment by mshipton** [comment]
Sorry, I submitted the bug report too soon. I have a lot more supporting information but will open a PR with proposed fix shortly.
