### ISSUE TITLE
flutter_cached_network_image show placeholder only

### ISSUE THREAD

**Issue by Ekeh** [renefloor/flutter_cached_network_image#113]
I am having issues using flutter_cached_network_image in my app. I have 
CachedNetworkImage(
imageUrl: url,
placeholder: new CircularProgressIndicator(),
errorWidget: new Icon(Icons.error)
This does not show the error icon but shows the progress indicator after the image is loaded.
Please where I am not getting right.

**Comment by dvaldivia** [comment]
Same problem

**Comment by dvaldivia** [comment]
Same problem happening on the latest flutter `1.1.2` on the `dev release`

**Comment by hieutrandn9889** [comment]
That bug still occurs on version 1.1.1
pls fix this bug
