### ISSUE TITLE
CachedNetworkImage does not load image within streambuilder (Image.network is working fine)

### ISSUE THREAD

**Issue by msw333** [renefloor/flutter_cached_network_image#114]
`Image.network(document['imageUrl']`
 
is working and shows image whereas 

```
CachedNetworkImage(imageUrl: document['imageUrl'],
       placeholder: new CircularProgressIndicator(),
       errorWidget: new Icon(Icons.error),
     )
```

only shows progress indicator (image is not loaded). Same issue for any remote url. Is it a bug?

Code: https://stackoverflow.com/questions/54131835/cachednetworkimage-only-shows-placeholder-and-doesnt-load-image-in-flutter-chat

**Comment by lifenautjoe** [comment]
Same here... Gets loaded fine first time, once a streambuilder emits, dissapears.

**Comment by msw333** [comment]
I just changed the properties which worked for me:
https://stackoverflow.com/questions/54131835/cachednetworkimage-only-shows-placeholder-and-doesnt-load-image-in-flutter-chat

**Comment by renefloor** [comment]
Strange..

**Comment by Satyam953** [comment]
1. Install the latest dependency for cached_network_image:
2. Stop the app if you are debugging or running
3. Flutter clean
4. Quite from IDE 
4. Reopen your IDE and run pub get
5. Run the app/web/...

**Comment by fairuzmn** [comment]
> 

thanks man, that's worked for me ♥️
