### ISSUE TITLE
ErrorWidget is not displayed when not network and not cached file

### ISSUE THREAD

**Issue by granoeste** [renefloor/flutter_cached_network_image#116]
When first time with not network connection and not cached file, throw  "Couldn't download or retreive file." Error. 
Why is not errorWidget displayed?

**Comment by CatEatFishs** [comment]
+1

**Comment by CatEatFishs** [comment]
I/flutter (29779): ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
I/flutter (29779): The following message was thrown resolving an image codec:
I/flutter (29779): Couldn't download or retreive file.
I/flutter (29779): 
I/flutter (29779): Image provider: CachedNetworkImageProvider("https://filedev.hongkazhijia.com", scale: 1.0)
I/flutter (29779): Image key: CachedNetworkImageProvider("https://filedev.hongkazhijia.com", scale: 1.0)

How to solve this problem？  thanks

**Comment by CatEatFishs** [comment]
I/flutter (29779): ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
I/flutter (29779): The following message was thrown resolving an image codec:
I/flutter (29779): Couldn't download or retreive file.
I/flutter (29779): 
I/flutter (29779): Image provider: CachedNetworkImageProvider("https://****.com", scale: 1.0)
I/flutter (29779): Image key: CachedNetworkImageProvider("https://****.com", scale: 1.0)

How to solve this problem？ thanks

**Comment by renefloor** [comment]
Should be fixed in 0.6.0.
