### ISSUE TITLE
MissingPluginException(No implementation found for method start on channel flutter_mobile_vision)

### ISSUE THREAD

**Issue by mohanarchu** [renefloor/flutter_cached_network_image#119]
I am using edofolly flutter vision plugin for ios, but is working in android devices properly, when i trying to install in ios device its installed successfully but my plugin is not imported error how can i fix this
...

**Comment by renefloor** [comment]
Maybe you could create an issue at that package instead of here. Or is it related to the cachednetworkimage?
The flutter_mobile_vision issues are here: https://github.com/edufolly/flutter_mobile_vision/issues
