### ISSUE TITLE
Not able to install new version cause shared_preferences

### ISSUE THREAD

**Issue by digarahayu** [renefloor/flutter_cached_network_image#121]
`Because cached_network_image >=0.5.0+1 <0.6.0-alpha depends on flutter_cache_manager ^0.2.0+1 which depends on shared_preferences ^0.4.0, cached_network_image >=0.5.0+1 <0.6.0-alpha requires shared_preferences ^0.4.0.
So, because think_clean depends on both cached_network_image ^0.5.1 and shared_preferences ^0.5.0, version solving failed.`

**Comment by renefloor** [comment]
Try 0.6.0
