### ISSUE TITLE
Image not updating if newly received url is the same

### ISSUE THREAD

**Issue by vanelizarov** [renefloor/flutter_cached_network_image#126]
To be more precise, I'm currently building user profile screen. It's a `StatelessWidget`, in which build method returns `StreamBuilder`, which depends on `user` stream. 
Each User has `avatar` property, which looks like this: `avatar/123456789`. `avatar` for one particular user is always the same, but contents of the file to which this url points may be different.
Current flow is the following:
1. Load new image into memory
2. Upload image to backend and receive avatar url on success
3. Copy current stored user into `nextUser`, put received avatar url in `nextUser`
4. Put `nextUser` in user stream

I've tried invalidating cache for avatar through `DefaultCacheManager.removeFile()` before sending `nextUser` into stream, but it didn't work

**Comment by renefloor** [comment]
With the new package you can also put a file in the cache. Does that work for you?

https://pub.dartlang.org/documentation/flutter_cache_manager/latest/flutter_cache_manager/BaseCacheManager/putFile.html

**Comment by vanelizarov** [comment]
I've tried it now, unfortunately not working. Sure it's putting new image's bytes in the cache, but the behavior is the following: image widget blinks like it's downloading new image and then shows the old one.

**Comment by vanelizarov** [comment]
Maybe there's a problem with Flutter's own image cache?..

**Comment by renefloor** [comment]
Could you provide a minimal code example that I can test?

**Comment by vanelizarov** [comment]
Sorry, I can't provide such minimal example, app's structure and logic is a bit complex.
I can provide some pieces of code, if it helps.

I'm using BLoC pattern.

Here's the "View" part:
```dart
StreamBuilder(
  stream: bloc.user, // rxdart's ReplaySubject instance 
  builder: (ctx, snapshot) {
    return CachedNetworkImage(
      imageUrl: 'https://torg.mts.ru/${user.avatar}',
      errorWidget: (c, u, e) => ImageError(),
      placeholder: (c, u) => ImagePlaceholder(),
      fit: BoxFit.cover,
    );
  }
)
``` 

And "BLoC" part:
```dart
Future<Null> updateAvatar(List<int> avatarBytes) async {
  try {
    final nextAvatar = await Api.user.setAvatar(
      MultipartFile.fromBytes('avatar', avatarBytes, filename: 'blob'),
    );
    final UserProfile nextUser = await lastUser;
    nextUser.avatar = '${json.decode(nextAvatar)}';
    await DefaultCacheManager().putFile('https://torg.mts.ru/${nextUser.avatar}', avatarBytes);
    user.add(nextUser);
  } on Exception {} 
}

Future<Null> getProfile({bool dropCachedAvatar = false}) async {
  try {
    final UserProfile nextUser = await Api.user.getProfile();
    if (dropCachedAvatar) {
      await DefaultCacheManager().removeFile('https://torg.mts.ru/${nextUser.avatar}');
    }
    user.add(nextUser);
  } on Exception {}
}
```

That's actually all the magic, nothing more. As I've said earlier, `user.avatar` is always the same for one particular user. Whe I pull to refresh, Refresh control calls `getProfile` with `dropCachedAvatar` set to `true`

I figured out that cached file is removed after calling `removeFile`, but I still can't understand why is it showing me the previous image

**Comment by renefloor** [comment]
I'll try to reproduce this, but I'm not completely sure if I understand it correctly.

**Comment by renefloor** [comment]
I guess this is fixed in the newer versions.
