### ISSUE TITLE
'ArgumentError' is not subtype of type 'Exception'

### ISSUE THREAD

**Issue by benadrasni** [renefloor/flutter_cached_network_image#127]
I tried to run _testContent() from your example and I've got the error 'ArgumentError' is not subtype of type 'Exception'. 

_addImage({FileInfo image, Exception error, Duration duration}) expect Exception, but it is getting ArgumentError.

**Comment by renefloor** [comment]
Thanks, I wasn't aware of that (I didn't test that part of the example again). Apparently Dart makes a distinction between errors and exceptions. When you don't have internet or the website cannot be reached, it gives an exception. However, when your url is just completely wrong and can't find the hostname it gives an error. For now I changed the example and just let the error continue to the developer as it should go.

**Comment by benjamindean** [comment]
@renefloor So, what's the solution for this? I tried wrapping it in try/catch, but no luck. Also, it throws HTTP exception on 404.

**Comment by renefloor** [comment]
I'll change this so it catches both

**Comment by didyqian** [comment]
When the url is wrong,  I had got the same error. Why is it that not go to the errorWidget?

**Comment by renefloor** [comment]
Fixed in 0.7.0
