### ISSUE TITLE
crashes when image has no permission in ^0.6.0+1

### ISSUE THREAD

**Issue by vuppalasivakumar** [renefloor/flutter_cached_network_image#129]
hi there,

App crashes when the image does not have a access permission in s3 bucket
when enter the same url in web:
AccessDeniedAccess DeniedA498B64C4F4F0AA2t2k1qMs0HyrqhpoDh4DHpu1H0R0wIZDH016asubJFiJmkN04ZN/U/jBUxdqMYd6UeX3cYvdI3tw=

flutter: Exception: Couldn't download or retreive file.

**Comment by renefloor** [comment]
@vuppalasivakumar does the app really crash, or does it only give the exception in the console? I compared the CachedNetworkImageProvider with the [NetworkImage](https://docs.flutter.io/flutter/painting/NetworkImage-class.html) of the Flutter framework, and that one also gives an exception in the console, for example when you don't have internet.
