### ISSUE TITLE
How to set CacheManager.showDebugLogs?

### ISSUE THREAD

**Issue by FastNinja** [renefloor/flutter_cached_network_image#13]
Hi Rene,

Given I do not reference CacheManager directly:

![image](https://user-images.githubusercontent.com/13673826/35190837-bbf45e12-febf-11e7-8fd2-b4c23c306d9e.png)

hod to I enable logs?

**Comment by renefloor** [comment]
You need to import the cache manager.
```
import 'package:flutter_cache_manager/flutter_cache_manager.dart';
```
In Intellij alt-enter should give that suggestion as well.

**Comment by hasonguo** [comment]
if (!_cacheData.containsKey(url))   
_cacheData is null wen i run crashed
The following NoSuchMethodError was thrown resolving an image codec:
The method 'containsKey' was called on null.
flutter: Receiver: null
flutter: Tried calling: containsKey("http://via.placeholder.com/350x200")
