### ISSUE TITLE
CachedNetworkImage not showing image in latest version

### ISSUE THREAD

**Issue by rzld** [renefloor/flutter_cached_network_image#130]
Since the latest version where the placeholder is using builders, the placeholder appears but the image doesn't show up (I'm using `CircularProgressIndicator` as the placeholder). I did not remember the exact words, but the error log said something about infinite heights.

**Comment by renefloor** [comment]
@rzld I guess this is the same issue as https://github.com/renefloor/flutter_cached_network_image/issues/128. Could you try to put the view in a SizedBox? For now I close this issue as duplicate.
