### ISSUE TITLE
While reloading a cached image, image position shows an "empty" instead of the placeholder

### ISSUE THREAD

**Issue by elricym** [renefloor/flutter_cached_network_image#133]
Hi, I have a long list with about 20 images at the same page. From my understanding, some images (let's say: set A) are removed from the memory when I scroll down a screen and the plugin loads other images (set B). If I scroll back, set A shows empty slots instead of placeholders while reloading them from the cache. In older versions, there are placeholders in the empty slots.

I think this problem is because of the new builder implementation for placeholder. Is there any 
way to keep a placeholder while images are removed from the memory? Or simply keep both placeholder widget and the builder properties, and then assert them not null at the same time.

This feature is somehow important to me. 
Thank you! I really love this plugin.

**Comment by renefloor** [comment]
Hmm that should not happen. It sounds like they aren't cached at all. Maybe something is wrong with the http headers? Could you share the urls? Then I can try to replicate this.

**Comment by elricym** [comment]
Thank you for your reply!
I actually tested out images randomly selected from the internet (for example amazon). Those images are about 120KB. I have to admit that my app is a little bit too complicated and that's why images are moved out from the memory quite often. The whole problem is that the placeholder should be there whatever the reason is, just like version 0.5.1 did. 

Images are like:
https://images-na.ssl-images-amazon.com/images/G/01/kindle/merch/2019/Trade-in/GW-Tall-Hero-3000x1200._CB455774835_.jpg

**Comment by renefloor** [comment]
Hmm I tried to replicate his with the image you've send, but for me the image just stayed visible.

**Comment by elricym** [comment]
Here is some screenshots for your reference.

Idle status of a long list view which contains about 20 images:
![simulator screen shot - iphone xs - 2019-03-01 at 12 28 35 copy](https://user-images.githubusercontent.com/8551749/53665996-cb113280-3c21-11e9-9495-f83bf0c07dbc.png)

This is how it works in version 0.5.1 when I scroll down and then scroll back.
![simulator screen shot - iphone xs - 2019-03-01 at 12 28 50 copy](https://user-images.githubusercontent.com/8551749/53666013-d5333100-3c21-11e9-993c-bc1312787388.png)

And the mechanism in 0.6.2:
![simulator screen shot - iphone xs - 2019-03-01 at 12 36 44 copy](https://user-images.githubusercontent.com/8551749/53666031-dc5a3f00-3c21-11e9-88dd-d26a615f6f55.png)

It clearly shows that there is always a placeholder however I scroll the list in 0.5.1. But after 0.6.0, placeholders only show in the initial loading procedure.

**Comment by renefloor** [comment]
Did this improve in 1.1.0?

**Comment by elricym** [comment]
@renefloor Thank you for your feedback. I've optimized a lot to work around this issue but I'm sure that offload images back with placeholders. Thank you so much for upgrading!
