### ISSUE TITLE
How to clip/crop image?

### ISSUE THREAD

**Issue by wiradikusuma** [renefloor/flutter_cached_network_image#136]
Assuming the image is not already square, the following does NOT clip the image:

	ClipRect(
		child: CachedNetworkImage(
			fit: BoxFit.fill, // "cover" does NOT work as well
			imageUrl: 'bla,
		),
	)

I've tried using `Align` in-between, doesn't work as well.

**Comment by renefloor** [comment]
Currently you need to set height and or width, for example to double.INFINITY, otherwise the image just takes it own size in the stack widget.
