### ISSUE TITLE
Bug in the cached_network_image library

### ISSUE THREAD

**Issue by azandrew-sidoine** [renefloor/flutter_cached_network_image#14]
Malformed Type line 38 : cannot resolve class "ImgageStreamCompleter" from CachedNetworkImageProvider 
ImageStreamCompleter load(CachedNetworkImageProvider key)
on Android 7.0

**Comment by renefloor** [comment]
Did you copy "ImgageStreamCompleter" wrongly or did it really state that? (See the extra g.)
Is your problem only on Android 7.0 or on every device, this should not be OS specific. 

Could you add the flutter doctor log?

**Comment by azandrew-sidoine** [comment]
The error happen on my Android 7.0 phone when the application was running
There is no problem with the flutter doctor
I try using the codes of your library directly in my app, change
ImageStreamCompleter class to MultiFrameImageStreamCompleter and the app
the image is load successfully now.
Don't know where issue is from
I download the library with the flutter package manager and reference it in
my code as mention in your readme

**Comment by azandrew-sidoine** [comment]
By the way do the plugin need Write permission to be added to
AndroidManifest.xml file?

**Comment by renefloor** [comment]
> The error happen on my Android 7.0 phone when the application was running

I was asking whether it happens only on Android 7.0 or whether it is also broken for you on other devices, for example the iOS simulator.

> There is no problem with the flutter doctor

I was mainly asking for flutter doctor as that also gives for example the version of Flutter you are using to build it. Maybe it is broken in a specific version of the Flutter SDK.

> I try using the codes of your library directly in my app, change
ImageStreamCompleter class to MultiFrameImageStreamCompleter and the app
the image is load successfully now.

The networkimage also uses the ImageStreamCompleter, does this one work for you?
```
  @override
  ImageStreamCompleter load(NetworkImage key) {
    return new MultiFrameImageStreamCompleter(
      codec: _loadAsync(key),
      scale: key.scale,
      informationCollector: (StringBuffer information) {
        information.writeln('Image provider: $this');
        information.write('Image key: $key');
      }
    );
  }
```

> By the way do the plugin need Write permission to be added to
AndroidManifest.xml file?

Should not be needed. It is not using external storage, for app storage you don't need a permission.

**Comment by azandrew-sidoine** [comment]
Found out that the issue was related to the flutter version was too old... Working now after updating. Thanks. Closing the issue
