### ISSUE TITLE
Because cached_network_image >=0.6.0 <0.6.2 depends on flutter_cache_manager ^0.3.0 which depends on path_provider ^0.5.0+1, cached_network_image >=0.6.0 <0.6.2 requires path_provider ^0.5.0+1. So, because nlite depends on both cached_network_image 0.6.1 and path_provider 0.4.1, version solving failed.

### ISSUE THREAD

**Issue by Allan-Nava** [renefloor/flutter_cached_network_image#142]
I have this pubspec.yaml:
  
  ```
dio: 2.0.0
  video_player: 0.5.1
  intl: ^0.15.2
  body_parser: 1.1.1
  dynamic_theme: 1.0.1
  package_info: 0.3.2+1
  image_picker: 0.4.12+1
  path_provider: 0.4.1
  #
  collection: 1.14.11
  device_info: 0.2.1
  connectivity: 0.3.2
  shared_preferences: 0.5.0
  flutter_range_slider: ^1.0.1
  onesignal: 1.0.3
  #
  cupertino_icons: ^0.1.2
```

And I get this error: 
```
Because cached_network_image >=0.6.0 <0.6.2 depends on flutter_cache_manager ^0.3.0 which depends on path_provider ^0.5.0+1, cached_network_image >=0.6.0 <0.6.2 requires path_provider ^0.5.0+1.
So, because nlite depends on both cached_network_image 0.6.1 and path_provider 0.4.1, version solving failed.

pub get failed (1)
```

**Comment by renefloor** [comment]
You should either use cached_network_image version 0.5.1 or path_provider 0.5.0+1. The newer version of both cached_network_image and path_provider asume the migration of Android Support Library to AndroidX, so the new version of one cannot be used with an old version of the other.

**Comment by Allan-Nava** [comment]
> 0.5.1 o

Okay thanks!

**Comment by Allan-Nava** [comment]
> You should either use cached_network_image version 0.5.1 or path_provider 0.5.0+1. The newer version of both cached_network_image and path_provider asume the migration of Android Support Library to AndroidX, so the new version of one cannot be used with an old version of the other.

Okay thank u! :)
