### ISSUE TITLE
Unhandled Exception: SocketException: OS Error: Connection reset by peer, errno = 104, address = www.wangyan.im, port = 38400

### ISSUE THREAD

**Issue by xiaoxiaocainiao** [renefloor/flutter_cached_network_image#145]
when request a image not exist, get this ERROR tip：

[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: SocketException: OS Error: Connection reset by peer, errno = 104, address = www.wangyan.im, port = 38400
E/flutter (23022): #0      BaseCacheManager.getFile (package:flutter_cache_manager/src/cache_manager.dart:120:11)
E/flutter (23022): <asynchronous suspension>
E/flutter (23022): #1      CachedNetworkImageState._animatedWidget (package:cached_network_image/src/cached_image_widget.dart:261:12)
E/flutter (23022): #2      CachedNetworkImageState.build (package:cached_network_image/src/cached_image_widget.dart:194:12)
E/flutter (23022): #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:3825:27)
E/flutter (23022): #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3736:15)
E/flutter (23022): #5      Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
E/flutter (23022): #6      StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
E/flutter (23022): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
E/flutter (23022): #8      RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4601:32)
E/flutter (23022): #9      MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992:17)
E/flutter (23022): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
E/flutter (23022): #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
E/flutter (23022): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
E/flutter (23022): #13     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
E/flutter (23022): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
E/flutter (23022): #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
E/flutter (23022): #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
E/flutter (23022): #17     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
E/flutter (23022): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
E/flutter (23022): #19     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
E/flutter (23022): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
E/flutter (23022): #21     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
E/flutter (23022): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
E/flutter (23022): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
E/flutter (23022): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
E/flutter (23022): #25     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
E/flutter (23022): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
E/flutter (23022): #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
E/flutter (23022): #28     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
E/flutter (23022): #29     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
E/flutter (23022): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
E/flutter (23022): #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
E/flutter (23022): #32     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
E/flutter (23022): #33     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
E/flutter (23022): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
E/flutter (23022): #35     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1030:36)
E/flutter (23022): #36     SliverMultiBoxAdaptorElement.performRebuild.processElement (package:flutter/src/widgets/sliver.dart:980:34)
E/flutter (23022): #37     List.forEach (dart:core/runtime/libgrowable_array.dart:278:8)
E/flutter (23022): #38     SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:991:36)
E/flutter (23022): #39     SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:957:7)
E/flutter (23022): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
E/flutter (23022): #41     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
E/flutter (23022): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
E/flutter (23022): #43     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4601

**Comment by xiaoxiaocainiao** [comment]
more information, the servier of the image is shuttered down or not exist anymore.

**Comment by renefloor** [comment]
Fixed in 1.1.0
