### ISSUE TITLE
Placeholder not being disposed upon image load

### ISSUE THREAD

**Issue by James-A-White** [renefloor/flutter_cached_network_image#146]
Thanks for the great component! Especially some of the improvements in 0.6.0.

I noticed the other day that my app drained my battery quite quickly. When I profiled the app, I saw that the screen was continuously refreshing even though nothing was changing on screen and there was no user interaction.

I traced it down to the placeholder widget in CachedNetworkImage. I'm specifying a CircularProgressIndicator to be used. When the progress indicator is displaying, naturally, the screen is getting refreshed. However, once the image loads and the progress indicator is no longer visible, the screen continues to be refreshed. As you can imagine this takes quite a bit of battery power. When I comment out the placeholder code, everything goes back to normal.

Is it possible that the placeholders are not being properly disposed of when they are no longer in use? I've verified this issue both on iOS and Android.  Thx again for this great piece of code! -JW

**Comment by renefloor** [comment]
Fixed in 1.1.0
