### ISSUE TITLE
CachedNetworkImageProvider need the placehoder and error handler to fix return new Image(image: new CachedNetworkImageProvider(swiper[index]));

### ISSUE THREAD

**Issue by jol5** [renefloor/flutter_cached_network_image#149]
CachedNetworkImageProvider need the placehoder and error handler to fix return new Image(image: new CachedNetworkImageProvider(swiper[index]));

i want to load net image with Swiper widget, and show the loading circle icon during loaded；
because the Swiper only adapt the Image Widget instead of  dynamic object,

**Comment by renefloor** [comment]
Sorry, ImageProviders can only return 1 image, otherwise I would have added that already. 
Can't you do something like this?
```
    body:  new Swiper(
       itemBuilder: (BuildContext context,int index){
            return CachedNetworkImage(
                imageUrl: "http://via.placeholder.com/350x150",
                placeholder: (context, url) => new CircularProgressIndicator(),
                errorWidget: (context, url, error) => new Icon(Icons.error),
            ,);
        },
        itemCount: 3,
        pagination: new SwiperPagination(),
        control: new SwiperControl(),
      ),
    );
```
