### ISSUE TITLE
After reloading and open the network image, it's show a error

### ISSUE THREAD

**Issue by ArvinCS** [renefloor/flutter_cached_network_image#15]
I don't know what happens
After reloading my app, and the network image became error
Error Log:
`E/flutter ( 2576): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter ( 2576): 'package:flutter/src/painting/image_stream.dart': Failed assertion: line 362 pos 12: '_codec != null': is not true.
E/flutter ( 2576): #0      _AssertionError._doThrowNew (dart:core-patch/dart:core/errors_patch.dart:37)
E/flutter ( 2576): #1      _AssertionError._throwNew (dart:core-patch/dart:core/errors_patch.dart:33)
E/flutter ( 2576): #2      MultiFrameImageStreamCompleter._handleCodecReady (package:flutter/src/painting/image_stream.dart:362:12)
E/flutter ( 2576): #3      _RootZone.runUnary (dart:async/zone.dart:1381)
E/flutter ( 2576): #4      _FutureListener.handleValue (dart:async/future_impl.dart:129)
E/flutter ( 2576): #5      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633)
E/flutter ( 2576): #6      _Future._propagateToListeners (dart:async/future_impl.dart:662)
E/flutter ( 2576): #7      _Future._completeError (dart:async/future_impl.dart:485)
E/flutter ( 2576): #8      _SyncCompleter._completeError (dart:async/future_impl.dart:55)
E/flutter ( 2576): #9      _Completer.completeError (dart:async/future_impl.dart:27)
E/flutter ( 2576): #10     CachedNetworkImageProvider._loadAsync (package:cached_network_image/cached_network_image.dart)
E/flutter ( 2576): <asynchronous suspension>
E/flutter ( 2576): #11     CachedNetworkImageProvider.load (package:cached_network_image/cached_network_image.dart:452:16)
E/flutter ( 2576): #12     ImageProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:266:86)
E/flutter ( 2576): #13     ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:82:22)
E/flutter ( 2576): #14     ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:266:63)
E/flutter ( 2576): #15     SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:38:29)
E/flutter ( 2576): #16     ImageProvider.resolve (package:flutter/src/painting/image_provider.dart:264:30)
E/flutter ( 2576): #17     _ImageProviderResolver.resolve (package:cached_network_image/cached_network_image.dart:190:29)
E/flutter ( 2576): #18     _CachedNetworkImageState._resolveImage (package:cached_network_image/cached_network_image.dart:276:20)
E/flutter ( 2576): #19     _CachedNetworkImageState.didChangeDependencies (package:cached_network_image/cached_network_image.dart:258:5)
E/flutter ( 2576): #20     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3734:12)
E/flutter ( 2576): #21     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3595:5)
E/flutter ( 2576): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885:14)
E/flutter ( 2576): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2688:12)
E/flutter ( 2576): #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3631:16)
E/flutter ( 2576): #25     Element.rebuild (package:flutter/src/widgets/framework.dart:3473:5)
E/flutter ( 2576): #26     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3600:5)
E/flutter ( 2576): #27     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3595:5)
E/flutter ( 2576): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885:14)
E/flutter ( 2576): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2688:12)
E/flutter ( 2576): #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3631:16)
E/flutter ( 2576): #31     Element.rebuild (package:flutter/src/widgets/framework.dart:3473:5)
E/flutter ( 2576): #32     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3600:5)
E/flutter ( 2576): #33     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3595:5)
E/flutter ( 2576): #34     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:3911:16)
E/flutter ( 2576): #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885:14)
E/flutter ( 2576): #36     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4711:32)
E/flutter ( 2576): #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885:14)
E/flutter ( 2576): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2688:12)
E/flutter ( 2576): #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3631:16)
E/flutter ( 2576): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3473:5)
E/flutter ( 2576): #41     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3600:5)
E/flutter ( 2576): #42     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3595:5)
E/flutter ( 2576): #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2885:14)
E/flutter ( 2576): #44 `

**Comment by renefloor** [comment]
`'_codec != null'` is thrown by the base class of the imageprovider and I couldn't find a quick way to ignore that error.
It should only be thrown when the image could not  be loaded from both the cache and the internet. Was it a new image that you tried to load the second time or was it an image from the cache?

**Comment by ArvinCS** [comment]
it's an image that load from cache, the image loaded(first time) and work before
sorry for my bad english

**Comment by ArvinCS** [comment]
Download Image -> Work -> Trying to load it again from cache -> error

**Comment by renefloor** [comment]
I cannot reproduce this.
Can you show me your code? A minimal example where it breaks for you would be best.
Are you working on iOS or Android and on a simulator or a real device?
What is your flutter version? A full `flutter doctor -v` output would be nice.

**Comment by ArvinCS** [comment]
My code:
`    var imagejadwal = new CachedNetworkImage(
      imageUrl: "https://www.dropbox.com/s/xw0mxii5jawdtby/fotopiket.jpg?dl=1",
      placeholder: new CircularProgressIndicator(),
      errorWidget: new Icon(Icons.error),
      fadeOutDuration: new Duration(seconds: 1),
      fadeInDuration: new Duration(seconds: 3),
      fit: BoxFit.cover,
      height: double.infinity,
      width: double.infinity,
      alignment: Alignment.center,
    );
`
Working on an android simulator

Flutter doctor -v output:
`[√] Flutter (on Microsoft Windows [Version 6.1.7601], locale id-ID, channel dev)
    • Flutter version 0.1.0 at C:\Users\arvin\flutter
    • Framework revision ab4506cad2 (5 days ago), 2018-02-09 12:21:43 -0800
    • Engine revision 337764e4ed
    • Tools Dart version 2.0.0-dev.22.0
    • Engine Dart version 2.0.0-edge.32396138ff733cbe8d9ac32178e6cffccdf80644

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at D:\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling s
upport)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = D:\AppData\Local\Android\sdk
    • Java binary at: D:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at D:\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] IntelliJ IDEA Community Edition (version 2017.3)
    • Flutter plugin version 21.1.3
    • Dart plugin version 173.4301.22

[!] VS Code (version 1.3.1)
    • VS Code at C:\Program Files (x86)\Microsoft VS Code
    • Dart Code extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code

[√] Connected devices
    • SM N935F • 127.0.0.1:62001 • android-x86 • Android 4.4.2 (API 19)

! Doctor found issues in 1 category.
`

**Comment by ArvinCS** [comment]
i think it's happened because it's downloaded from Dropbox. i tested with google drive and it works fine

**Comment by ArvinCS** [comment]
`    var switchButton = new Switch(
        value: detail,
        onChanged: (bool value){
          setState(() {
            detail = value;
          });
        },
    );

    var imagejadwal = new CachedNetworkImage(
      imageUrl: switchButton.value?"https://drive.google.com/uc?export=download&id=1v-dA5bG7Fwk_hJvL2wu4Z9P10JdsaWIe":"https://drive.google.com/uc?export=download&id=1qfdI_yM7rzdLMqRizlr76445qc0IQKhD",
      placeholder: new CircularProgressIndicator(),
      errorWidget: new Icon(Icons.error),
    );`

do you know why the image doesn't change?

**Comment by renefloor** [comment]
The last one is a bit tricky. It is already in the state that it thinks the url is loaded probably. This is also not really clear whether you want to show the ProgressIndicator again, or just want to go from one image to the other when it is ready. Probably you can better just use the imageprovider directly and have a look at the implementation of `CachedNetworkImage` and try to make something yourself. You could also just build a different CachedNetworkImage based on the switch.

I found the problem of your image. First of all it is a bit strange to use an image from dropbox, also because it indicates it as a binary file. But the problem was that dropbox says the file is valid for only 60 seconds, so the next time you start the app (after 60 seconds) it asks again whether the file is still valid or not. Dropbox says it is still valid (with a 304), but doesn't give a new period for that anymore, so after that it will check every time you use the file. 

The problem was I used `_cacheData[url].validTill.toIso8601String()` for logging and that gave a nullpointer because the validTill is null. I will fix that, but I do encourage you to not use that dropbox url with this library.
