### ISSUE TITLE
image can not be made rounded/circular

### ISSUE THREAD

**Issue by aytunch** [renefloor/flutter_cached_network_image#156]
If the original network image is rectangular, even by using `ClipRRect` and `fit: BoxFit.cover`, we can not make the resulting widget square and rounded.

**Comment by hasimyerlikaya** [comment]
You can use with imageBuilder like me.

`  imageBuilder: (context, image) {
                  return ClipRRect(
                      borderRadius: new BorderRadius.circular(8.0),
                      child: Image(
                        image: image,
                        gaplessPlayback: true,
                        fit: BoxFit.cover,
                      ));
                },`

**Comment by ronpetit** [comment]
As the previous post suggested, you can use ClipRRect to give a border radius to you image, but if you want t perfect circle you can use ClipOval
Example:

```dart
ClipOval(child: Image(image, fit: BoxFit.cover))
```

PD: The "image" needs to be a image provider

**Comment by renefloor** [comment]
I also added an example to the readme for using the imageBuilder.
