### ISSUE TITLE
ChangeLog should show AndroidX breaking change

### ISSUE THREAD

**Issue by GustavoContreiras** [renefloor/flutter_cached_network_image#158]
`Because cached_network_image >=0.7.0 depends on flutter_cache_manager ^0.3.2 which depends on path_provider ^0.5.0+1, cached_network_image >=0.7.0 requires path_provider ^0.5.0+1.`

Like every other package on https://pub.dartlang.org/packages/ cached_network_image should show the AndroidX breaking change too.

I'm using ^0.5.1 to avoid AndroidX.

**Comment by renefloor** [comment]
Sorry for that. 0.6.0 already had a lot of breaking changes, but should have added that indeed.
Are you still using 0.5.1?
