### ISSUE TITLE
Please provide upgrade path when doing breaking changes

### ISSUE THREAD

**Issue by Cretezy** [renefloor/flutter_cached_network_image#160]
Releases 0.6.0, 0.6.1, and 0.7.0 all have breaking changes, with almost no upgrade documentation (one liner for 0.6.0 in README). This should be heavily discouraged because it makes it very hard to track down what broke, and how to upgrade it.

This is a great package, but going forward, please try to include better documentation when doing breaking changes! (Also, 0.6.1 shouldn't of had breaking changes either, since it's a minor realease)

**Comment by renefloor** [comment]
Yes sorry. Will do that in the future.
