### ISSUE TITLE
Images are not loading

### ISSUE THREAD

**Issue by AdamBCo** [renefloor/flutter_cached_network_image#163]
I am currently using version 0.7.0 in my flutter example.

When copy and pasting the example code in a widget, the image never loads:

`
new CachedNetworkImage(
        imageUrl: "http://via.placeholder.com/350x150",
        placeholder: (context, url) => new CircularProgressIndicator(),
        errorWidget: (context, url, error) => new Icon(Icons.error),
     )

`

I just see the progressIndicator the entire time.

**Comment by tiancanfei** [comment]
I met the same problem

**Comment by arma7x** [comment]
same here

**Comment by sandaru1** [comment]
Hot reloading doesn't work because of the dependencies.

You should stop the app and do a re-build. The rebuild would run "pod install" and this problem would be solved.

**Comment by arma7x** [comment]
thank @sandaru1. Solve my issues...

**Comment by tiancanfei** [comment]
FlutterViewController *vc = [[FlutterViewController alloc] init];
    [GeneratedPluginRegistrant registerWithRegistry:vc];
    [self presentViewController:vc animated:YES completion:nil];
     I don't have registed plugin.

**Comment by tomosullivan8** [comment]
Same issue

**Comment by arma7x** [comment]
Use command `flutter run` instead `flutter attach` after install this package to build new apk and install on connected device

**Comment by chenzhentao** [comment]
there is first of images failure to load every time
but i use image.network(),all would load well

**Comment by renefloor** [comment]
I guess this should be working fine by now. I not please reopen.
