### ISSUE TITLE
There is an exception if i use empty url and it always blocking me to debug application properly , i am using version 0.7.0

### ISSUE THREAD

**Issue by ch-muhammad-adil** [renefloor/flutter_cached_network_image#167]
<img width="1392" alt="Screenshot 2019-04-24 at 10 04 33 AM" src="https://user-images.githubusercontent.com/8264639/56633872-4cf96700-6679-11e9-9f72-2b98c2dad00c.png">

**Comment by renefloor** [comment]
Should be fixed in 1.1.0
