### ISSUE TITLE
application crashes when image url returns 404

### ISSUE THREAD

**Issue by m7mdra** [renefloor/flutter_cached_network_image#170]
When i try to load an image using the library sometimes the image may not be available the application then crashes even thought i used `errorWidget` in the constructor.
here is my example:
```
 CachedNetworkImage(
                    imageUrl: userPayload.photo,
                    width: 90,
                    height: 90,
                    placeholder: (context, url) {
                      return DefaultUserAvatarWidget();
                    },
                    errorWidget: (context, url, error) {
                      return DefaultUserAvatarWidget();
                    },
                  )
```
error:  
`HttpException (HttpException: No valid statuscode. Statuscode was 404)`

**Comment by codememory101** [comment]
Same happens for me.

**Comment by aerozavr** [comment]
same here

**Comment by marrullas** [comment]
X 4

**Comment by shpy2001** [comment]
Same for me.

**Comment by ushang000** [comment]
+1

**Comment by lifetin** [comment]
+1

**Comment by lifetin** [comment]
I/flutter ( 5552): 图片加载失败https://img.alicdn.com/imgextra/i4/2115644366/O1CN01xXfonL1i7fixv6Mw1_!!2115644366.jpg_300x300.jpg
I/flutter ( 5552): No valid statuscode. Statuscode was 404
I/flutter ( 5552): 图片加载失败https://img.alicdn.com/imgextra/i4/2115644366/O1CN01xXfonL1i7fixv6Mw1_!!2115644366.jpg_300x300.jpg
I/flutter ( 5552): No valid statuscode. Statuscode was 404
I/flutter ( 5552): onNotifySetState=>onHttpSuccess

**Comment by 229106948** [comment]
same here

**Comment by jlnr** [comment]
Is this a duplicate of #144 (fix in #190)?

**Comment by renefloor** [comment]
Fixed

**Comment by charleshan** [comment]
@renefloor still happening in `1.1.1`.
