### ISSUE TITLE
[bug] Direct compilation of errors under the latest version of flutter

### ISSUE THREAD

**Issue by elinxer** [renefloor/flutter_cached_network_image#176]
flutter version： v1.5.8
all is newest at this time, i just import and then compilation throw this error.

![image](https://user-images.githubusercontent.com/7327251/57635795-781d0980-75da-11e9-9ca6-259a88c765e5.png)
```
Compiler message:
file:///home/elinx/.pub-cache/hosted/pub.flutter-io.cn/cached_network_image-0.6.2/lib/src/cached_network_image_provider.dart:46:31: Error: The argument type 'Null Function(StringBuffer)' can't be assigned to the parameter type 'Iterable<DiagnosticsNode> Function()'.
 - 'StringBuffer' is from 'dart:core'.
 - 'Iterable' is from 'dart:core'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///home/elinx/app/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'Iterable<DiagnosticsNode> Function()'.
        informationCollector: (StringBuffer information) {
```

**Comment by SGZoom** [comment]
v1.5.9-pre.258  

cached_network_image-0.4.2/lib/cached_network_image.dart:464:31: Error: The argument type 'Null Function(StringBuffer)' can't be assigned to the parameter type 'Iterable<DiagnosticsNode> Function()'.
 - 'StringBuffer' is from 'dart:core'.
 - 'Iterable' is from 'dart:core'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///E:/softeware/flutter/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'Iterable<DiagnosticsNode> Function()'.
        informationCollector: (StringBuffer information) {
                              ^

**Comment by renefloor** [comment]
That's exactly why I released version 0.8.0.

**Comment by elinxer** [comment]
Thinks you are.

**Comment by SGZoom** [comment]
Thank you :)
