### ISSUE TITLE
cached_network_image >=0.7.0 depends on flutter_cache_manager ^0.3.2 which depends on path_provider ^0.5.0+1 , Meanwhile path_provider already 1.1.0

### ISSUE THREAD

**Issue by digarahayu** [renefloor/flutter_cached_network_image#180]
Because cached_network_image >=0.7.0 depends on flutter_cache_manager ^0.3.2 which depends on path_provider ^0.5.0+1, cached_network_image >=0.7.0 requires path_provider ^0.5.0+1.
So, because gebyar depends on both cached_network_image ^0.8.0 and path_provider ^1.1.0, version solving failed

**Comment by Bernix01** [comment]
seems to be related to [flutter_cache_manager](https://github.com/renefloor/flutter_cache_manager) which is maintained by @renefloor too! There is pr open for this see [#85](https://github.com/renefloor/flutter_cache_manager/pull/85).

**Comment by sawankumarbundelkhandi** [comment]
Override dependency until the pull request [#85](https://github.com/renefloor/flutter_cache_manager/pull/85) is merged.

https://dart.dev/tools/pub/dependencies#dependency-overrides

dependency_overrides:
  path_provider: ^1.1.0

**Comment by renefloor** [comment]
Fixed
