### ISSUE TITLE
Advantage over FadeInImage?

### ISSUE THREAD

**Issue by btastic** [renefloor/flutter_cached_network_image#19]
Hey there,

I just saw your library and looked at some of the code and it seems to be very similar to what [FadeInImage](https://docs.flutter.io/flutter/widgets/FadeInImage-class.html) does.

What are the main differences / advantages over FadeInImage?

**Comment by renefloor** [comment]
Previously I also suggested to use FadeInImage to fade from a placeholder to the cachednetworkimage. If you want to do that I even think FadeInImage is the better option in combination with a CachedNetworkImageProvider. I got quite some requests to also have an option for a placeholder widget, such as a progressindicator, and a seperate widget for when the image fails to load. These two are not possible with FadeInImage and for those options you can use the CachedNetworkImage. 
As I could not find a way to catch the error in a generic ImageProvider I had to couple it with my own imageprovider. I will probably have a look at the flutter source and submit a pull request to have this option in all imageproviders and then I will probably make the CachedNetworkImage more generic for all imageproviders.
