### ISSUE TITLE
after flutter upgrade. compatblity was broken

### ISSUE THREAD

**Issue by memetea** [renefloor/flutter_cached_network_image#192]
hi. the library was not compatible with latest flutter.

compiler error:
======================================================
Compiler message:
file:///E:/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-0.5.1/lib/cached_network_image.dart:199:38: Error: The argument type 'void Function(ImageInfo, bool)' can't be assigned to the parameter type 'ImageStreamListener'.
 - 'ImageInfo' is from 'package:flutter/src/painting/image_stream.dart' ('file:///E:/flutter/packages/flutter/lib/src/painting/image_stream.dart').
 - 'ImageStreamListener' is from 'package:flutter/src/painting/image_stream.dart' ('file:///E:/flutter/packages/flutter/lib/src/painting/image_stream.dart').
Try changing the type of the parameter, or casting the argument to 'ImageStreamListener'.
      oldImageStream?.removeListener(_handleImageChanged);

flutter doctor:
=======================================================
Flutter 1.6.3 • channel beta • https://github.com/flutter/flutter.git
Framework • revision bc7bc94083 (11 days ago) • 2019-05-23 10:29:07 -0700
Engine • revision 8dc3a4cde2
Tools • Dart 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)

Running "flutter pub upgrade" in mobile...                         42.9s

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v1.6.3, on Microsoft Windows [Version 10.0.17134.706], locale zh-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    X Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Android Studio (version 3.4)
[√] VS Code (version 1.34.0)
[√] Connected device (1 available)

! Doctor found issues in 1 category.

**Comment by MauriPastorini** [comment]
Have you got the last version 0.8.0 ? I had a similar problem and got fixed with this last version

**Comment by memetea** [comment]
@MauriPastorini      the upgrade solved this problem.   thank you!

**Comment by iPatel007** [comment]
> 0.8.0

Work for me :)
