### ISSUE TITLE
error

### ISSUE THREAD

**Issue by sunguotao** [renefloor/flutter_cached_network_image#193]
`
Compiler message:
file:///Users/sunguotao/.pub-cache/hosted/pub.flutter-io.cn/cached_network_image-0.7.0/lib/src/cached_network_image_provider.dart:46:31: Error: The argument type 'Null Function(StringBuffer)' can't be assigned to the parameter type 'Iterable<DiagnosticsNode> Function()'.
 - 'StringBuffer' is from 'dart:core'.
 - 'Iterable' is from 'dart:core'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///Users/sunguotao/Desktop/AndroidDev/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'Iterable<DiagnosticsNode> Function()'.
        informationCollector: (StringBuffer information) {
                              ^
Compiler failed on /Users/sunguotao/Desktop/QIQU/flutter_app/lib/main.dart

FAILURE: Build failed with an exception.

* Where:
Script '/Users/sunguotao/Desktop/AndroidDev/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 648

* What went wrong:
Execution failed for task ':app:compileflutterBuildDebugandroid-arm64'.
> Process 'command '/Users/sunguotao/Desktop/AndroidDev/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.`

**Comment by MauriPastorini** [comment]
Have you got the last version 0.8.0 ? I had a similar problem and got fixed with this last version

**Comment by sm9i** [comment]
我现在也是这个问题 ` - 'StringBuffer' is from 'dart:core'.
 - 'Iterable' is from 'dart:core'.`

是不是要换到 hotfixes? 我现在是 master分支

**Comment by renefloor** [comment]
Should be fixed in newer versions as said.
