### ISSUE TITLE
Same url with different images.

### ISSUE THREAD

**Issue by iPatel007** [renefloor/flutter_cached_network_image#196]
Issue occurs when url of image stay it is but image will be changed. I have asked question on 
[StackOverFlow](https://stackoverflow.com/questions/56562884/cachednetworkimage-image-does-not-change-with-same-name) Please look into that.

**Comment by renefloor** [comment]
See my answer on 208. But as the answer on stackoverflow, not sure if this package is the right solution for your problem.
