### ISSUE TITLE
Download image with specified size

### ISSUE THREAD

**Issue by ManojMM026** [renefloor/flutter_cached_network_image#198]
I would like to download an image with a specified size, In my case, I have very big images around 2450X1440 resolution. For Grid and list, I don't need a full size, I would like to load thumbnail of it lets say around 200X200. Please let me know how can I achieve it here.

I tried doing scale, Nothing happened

**Comment by renefloor** [comment]
You could use different urls for them. How would you want to see this. If you have cached the bigger one once always use that one?

**Comment by ManojMM026** [comment]
Yes at the moment I have created 2 different images thumbnail and original, I am fetching them differently. But I would love to have a downscaling image with provided dimension.
