### ISSUE TITLE
Is it possible to use a retry strategy?

### ISSUE THREAD

**Issue by Luk3s** [renefloor/flutter_cached_network_image#20]
Is there a way to use the cached network image plugin together with the [NetworkImageWithRetry plugin](https://pub.dartlang.org/packages/flutter_image)? I'd like to use a retry strategy but I don't know how to connect the two plugins since both require the image url and retrieve the image.

**Comment by renefloor** [comment]
No those cannot be combined as they are both ImageProviders. You could have a look at the code and try to combine them. You could use something like this with the cachemanager I use in this library:
```
        request = await _client.getUrl(instructions.uri).timeout(instructions.timeout);
        final io.HttpClientResponse response = await request.close().timeout(instructions.timeout);

        if (response == null || response.statusCode != 200) {
          throw new FetchFailure._(
            totalDuration: stopwatch.elapsed,
            attemptCount: attemptCount,
            httpStatusCode: response.statusCode,
          );
        }
```

**Comment by danielgomezrico** [comment]
@renefloor I dont understand your proposed solution, to us it is pretty important to add this strategy, is there any way that you could add some comments around how could this be done to the library and maybe I could make the contribution?

**Comment by markwitt1** [comment]
Any updates on this?
