### ISSUE TITLE
Flutter 1.7.8+hotfix.3 Error: The argument type 'Null Function(StringBuffer)'

### ISSUE THREAD

**Issue by puneetsdsharma65** [renefloor/flutter_cached_network_image#203]
Compiler message:
file:///Users/xyz/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_image-1.0.0/lib/network.dart:75:31: Error: The argument type 'Null Function(StringBuffer)' can't be assigned to the parameter type 'Iterable Function()'.

'StringBuffer' is from 'dart:core'.
'Iterable' is from 'dart:core'.
'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///Users/xyz/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'Iterable Function()'.
informationCollector: (StringBuffer information) {
on **stable channel** version
**Flutter 1.7.8+hotfix.3**

Thanks

**Comment by craiglabenz** [comment]
Why was this issue closed? fwiw, I'm currently seeing a very similar error on CNI version `0.6.2` and Flutter `1.7.8+hotfix.3`.

```
Compiler message:
file:///.../flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-0.6.2/lib/src/cached_network_image_provider.dart:46:31: Error: The argument type 'Null Function(StringBuffer)' can't be assigned to the parameter type 'Iterable<DiagnosticsNode> Function()'.
 - 'StringBuffer' is from 'dart:core'.
 - 'Iterable' is from 'dart:core'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///.../flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'Iterable<DiagnosticsNode> Function()'.
        informationCollector: (StringBuffer information) {
                              ^
Compiler failed on /Users/craiglabenz/Sites/coop/mobile/lib/main_dev.dart
```

**Comment by SahSantoshh** [comment]
any progress for this issue for Flutter `1.7.8+hotfix.3`
