### ISSUE TITLE
flutter1.7.8 Error: The argument type 'String' can't be assigned to the parameter type 'DiagnosticsNode'.

### ISSUE THREAD

**Issue by puneetsdsharma65** [renefloor/flutter_cached_network_image#204]
Error: The argument type 'String' can't be assigned to the parameter type 'DiagnosticsNode'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///Users/xyz/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'DiagnosticsNode'.
      context: '$runtimeType failed to load ${instructions.uri}'

channel : stable
version 1.7.8

Thanks

**Comment by DavidYang1121** [comment]
I have the same error!

**Comment by DavidYang1121** [comment]
@mshipton @victorbonnet @aschulz90

**Comment by DavidYang1121** [comment]
@puneetsdsharma65 The version 1.0.0 has fixed the error, you can have a try.

**Comment by renefloor** [comment]
@puneetsdsharma65 which version of the cached_network_image are you using?

**Comment by puneetsdsharma65** [comment]
Yah Issue is fixed, I have updated flutter_image 1.0.0 to 2.0.0 in pubspec.yaml, that was using in my flutter_map

Thanks
