### ISSUE TITLE
Add authentication header 

### ISSUE THREAD

**Issue by stefanschaller** [renefloor/flutter_cached_network_image#21]
In some use cases authentication is needed in order the get access to the image.

**Comment by renefloor** [comment]
That is indeed a good idea. I guess it would be easy to just add headers in general.

**Comment by stefanschaller** [comment]
Yes, ecxacly. This can be the perfekt complication. 
Thank you!

**Comment by renefloor** [comment]
@stefanschaller I just added optional headers. I didn't test it thoroughly yet, could you try if it works for you? It is in the release of `0.4.0-rc.1`. You should use `httpHeaders` on the `CachedNetworkImage` or just `headers` in the `CachedNetworkImageProvider`.
