### ISSUE TITLE
gif

### ISSUE THREAD

**Issue by wang-zeqi** [renefloor/flutter_cached_network_image#222]
The gif of the network picture shows only a static picture. What is the reason?

**Comment by feudadrien** [comment]
can you show code?

**Comment by wang-zeqi** [comment]
Container(
                  child: CachedNetworkImage(
                  imageUrl: _hanger,
                  width: _imageWidth + _imageWidth / 9,
                  height: _imageWidth + _imageWidth / 9,
                ))

**Comment by wang-zeqi** [comment]
Thank you. I've solved it. It's not a code problem. I'm sorry.

**Comment by liuyifeng93** [comment]
> I've solved it. It's not a code problem. I'm sorry.

hi， I've same issure，call you tell me what happend, Thanks!
