### ISSUE TITLE
I set the CircularProgressIndicator's size by a wrapped SizedBox in CachedNetworkImage's placeholder.But it didn't work.

### ISSUE THREAD

**Issue by nightfallsad** [renefloor/flutter_cached_network_image#225]
I want change the CircularProgressIndicator size and I used a SizedBox wrapped it.
But if I not used SizedBox in CachedNetworkImage's placeholder,it worked.
CachedNetworkImage(
                          fit: BoxFit.fill,
                          imageUrl: 'imageUrl',
                          placeholder: (context, url) =>
                            SizedBox(
                              width: 10.0,
                              height: 10.0,
                              child: CircularProgressIndicator(
                                valueColor: AlwaysStoppedAnimation(Colors.green),
                              ),
                            )
                        )
![微信截图_20190823145154](https://user-images.githubusercontent.com/23025607/63573333-a043dd80-c5b7-11e9-97d0-c8dd54f10f72.png)

**Comment by Bishel** [comment]
Wrap SizedBox with Center widget

```
CachedNetworkImage(
  imageUrl: 'ImageUrl',
  fit: BoxFit.cover,
  placeholder: (context, url) => Center(
    child: SizedBox(
      width: 40.0,
      height: 40.0,
      child: new CircularProgressIndicator(),
    ),
  ),
  errorWidget: (context, url, error) => new Icon(Icons.error),
)
```

**Comment by nightfallsad** [comment]
> Wrap SizedBox with Center widget
> 
> ```
> CachedNetworkImage(
>   imageUrl: 'ImageUrl',
>   fit: BoxFit.cover,
>   placeholder: (context, url) => Center(
>     child: SizedBox(
>       width: 40.0,
>       height: 40.0,
>       child: new CircularProgressIndicator(),
>     ),
>   ),
>   errorWidget: (context, url, error) => new Icon(Icons.error),
> )
> ```

Thanks.
