### ISSUE TITLE
Load Cached Image When Offline

### ISSUE THREAD

**Issue by putraxor** [renefloor/flutter_cached_network_image#24]
Hi, this plugin can't load cached image when network goes offline

**Comment by renefloor** [comment]
Could you give me the url of the image you try to load and give the debug output from the cachemanager using the following line at the start of your app: `CacheManager.showDebugLogs = true;`

**Comment by renefloor** [comment]
@putraxor I might have fixed this in `0.4.0-rc.1` as there was some bug in the cache cleaning. If not, could you help me with the logs?

**Comment by putraxor** [comment]
Thanks, now it's working renefloor
