### ISSUE TITLE
Image not changing when useOldImageOnUrlChange = true

### ISSUE THREAD

**Issue by mdc555** [renefloor/flutter_cached_network_image#241]
I've just updated the version number to 1.1.1 and I've noticed that the image won't change when useOldImageOnUrlChange = true. This was working normally with previous versions.
If I change useOldImageOnUrlChange to false it will change the image but with an undesired flicker.

**Comment by Kavantix** [comment]
@mdc555 Can you check if my PR fixes your issue?
