### ISSUE TITLE
Failed assertion: line 362: '_codec != null': is not true

### ISSUE THREAD

**Issue by KingIdee** [renefloor/flutter_cached_network_image#26]
03-27 18:35:38.411 3414-3429/com.yourcompany.rickandmorty E/flutter: [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
                                                                     'package:flutter/src/painting/image_stream.dart': Failed assertion: line 362: '_codec != null': is not true.
                                                                     #0      _AssertionError._doThrowNew (dart:core-patch/dart:core/errors_patch.dart:37)
                                                                     #1      _AssertionError._throwNew (dart:core-patch/dart:core/errors_patch.dart:33)
                                                                     #2      MultiFrameImageStreamCompleter._handleCodecReady (package:flutter/src/painting/image_stream.dart:362)
                                                                     #3      _RootZone.runUnary (dart:async/zone.dart:1381)
                                                                     #4      _FutureListener.handleValue (dart:async/future_impl.dart:129)
                                                                     #5      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633)
                                                                     #6      _Future._propagateToListeners (dart:async/future_impl.dart:662)
                                                                     #7      _Future._completeError (dart:async/future_impl.dart:485)
                                                                     #8      _SyncCompleter._completeError (dart:async/future_impl.dart:55)
                                                                     #9      _Completer.completeError (dart:async/future_impl.dart:27)
                                                                     #10     CachedNetworkImageProvider._loadAsync (package:cached_network_image/cached_network_image.dart)
                                                                     <asynchronous suspension>
                                                                     #11     CachedNetworkImageProvider.load (package:cached_network_image/cached_network_image.dart:452)
                                                                     #12     ImageProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:266)
                                                                     #13     ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:82)
                                                                     #14     ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:266)
                                                                     #15     SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:38)
                                                                     #16     ImageProvider.resolve (package:flutter/src/painting/image_provider.dart:264)
                                                                     #17     _ImageProviderResolver.resolve (package:cached_network_image/cached_network_image.dart:190)
                                                                     #18     _CachedNetworkImageState._resolveImage (package:cached_network_image/cached_network_image.dart:276)
                                                                     #19     _CachedNetworkImageState.didChangeDependencies (package:cached_network_image/cached_network_image.dart:258)
                                                                     #20     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3739)
                                                                     #21     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
                                                                     #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
                                                                     #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
                                                                     #24     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4611)
                                                                     #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
                                                                     #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
                                                                     #27     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4611)
                                                                     #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
                                                                     #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
                                                                     #30     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4611)
                                                                     #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
                                                                     #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
                                                                     #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
                                                                     #34     Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
                                                                     #35     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605)
                                                                     #36     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
                                                                     #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
                                                                     #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
                                                                     #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
                                                                     #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
                                                                     #41     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605)
                                                                     #42     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
                                                                     #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
                                                                     #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
                                                                     #45     Com
03-27 18:35:38.460 3414-3429/com.yourcompany.rickandmorty E/flutter: [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
                                                                     NoSuchMethodError: The method 'toMap' was called on null.
                                                                     Receiver: null
                                                                     Tried calling: toMap()
                                                                     #0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
                                                                     #1      CacheManager._saveDataInPrefs.<anonymous closure>.<anonymous closure> (package:flutter_cache_manager/flutter_cache_manager.dart:108)
                                                                     #2      _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/dart:collection/compact_hash.dart:361)
                                                                     #3      CacheManager._saveDataInPrefs.<anonymous closure> (package:flutter_cache_manager/flutter_cache_manager.dart:107)
                                                                     #4      SynchronizedLock._runTask.<anonymous closure>.<anonymous closure> (package:synchronized/src/synchronized_impl.dart:194)
                                                                     #5      _rootRun (dart:async/zone.dart:1126)
                                                                     #6      _CustomZone.run (dart:async/zone.dart:1023)
                                                                     #7      runZoned (dart:async/zone.dart:1501)
                                                                     #8      SynchronizedLock._runTask.<anonymous closure> (package:synchronized/src/synchronized_impl.dart:192)
                                                                     #9      new Future.sync (dart:async/future.dart:222)
                                                                     #10     SynchronizedLock._runTask (package:synchronized/src/synchronized_impl.dart:191)
                                                                     #11     LockBase._createAndRunTask.run (package:synchronized/src/synchronized_impl.dart:66)
                                                                     #12     LockBase._createAndRunTask (package:synchronized/src/synchronized_impl.dart:76)
                                                                     #13     SynchronizedLock.synchronized (package:synchronized/src/synchronized_impl.dart:227)
                                                                     #14     synchronized (package:synchronized/src/synchronized_impl.dart:280)
                                                                     #15     synchronized (package:synchronized/synchronized.dart:47)
                                                                     #16     CacheManager._saveDataInPrefs (package:flutter_cache_manager/flutter_cache_manager.dart:106)
                                                                     <asynchronous suspension>
                                                                     #17     CacheManager._save (package:flutter_cache_manager/flutter_cache_manager.dart:78)
                                                                     <asynchronous suspension>
                                                                     #18     CacheManager.getFile (package:flutter_cache_manager/flutter_cache_manager.dart:231)
                                                                     <asynchronous suspension>
                                                                     #19     CachedNetworkImageProvider._loadAsync (package:cached_network_image/cached_network_image.dart:464)
                                                                     <asynchronous suspension>
                                                                     #20     CachedNetworkImageProvider.load (package:cached_network_image/cached_network_image.dart:452)
                                                                     #21     ImageProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:266)
                                                                     #22     ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:82)
                                                                     #23     ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:266)
                                                                     #24     SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:38)
                                                                     #25     ImageProvider.resolve (package:flutter/src/painting/image_provider.dart:264)
                                                                     #26     _ImageProviderResolver.resolve (package:cached_network_image/cached_network_image.dart:190)
                                                                     #27     _CachedNetworkImageState._resolveImage (package:cached_network_image/cached_network_image.dart:276)
                                                                     #28     _CachedNetworkImageState.didChangeDependencies (package:cached_network_image/cached_network_image.dart:258)
                                                                     #29     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3739)
                                                                     #30     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
                                                                     #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
                                                                     #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
                                                                     #33     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4611)
                                                                     #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
                                                                     #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
                                                                     #36     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4611)
                                                                     #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
                                                                     #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
                                                                     #39     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4611)
                                                                     #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
                                                                     #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
                                                                     #42     ComponentEl
03-27 18:35:38.511 3414-3429/com.yourcompany.rickandmorty E/flutter: [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
                                                                     'package:flutter/src/painting/image_stream.dart': Failed assertion: line 362: '_codec != null': is not true.
                                                                     #0      _AssertionError._doThrowNew (dart:core-patch/dart:core/errors_patch.dart:37)
                                                                     #1      _AssertionError._throwNew (dart:core-patch/dart:core/errors_patch.dart:33)
                                                                     #2      MultiFrameImageStreamCompleter._handleCodecReady (package:flutter/src/painting/image_stream.dart:362)
                                                                     #3      _RootZone.runUnary (dart:async/zone.dart:1381)
                                                                     #4      _FutureListener.handleValue (dart:async/future_impl.dart:129)
                                                                     #5      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633)
                                                                     #6      _Future._propagateToListeners (dart:async/future_impl.dart:662)
                                                                     #7      _Future._completeError (dart:async/future_impl.dart:485)
                                                                     #8      _SyncCompleter._completeError (dart:async/future_impl.dart:55)
                                                                     #9      _Completer.completeError (dart:async/future_impl.dart:27)
                                                                     #10     CachedNetworkImageProvider._loadAsync (package:cached_network_image/cached_network_image.dart)
                                                                     <asynchronous suspension>
                                                                     #11     CachedNetworkImageProvider.load (package:cached_network_image/cached_network_image.dart:452)
                                                                     #12     ImageProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:266)
                                                                     #13     ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:82)
                                                                     #14     ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:266)
                                                                     #15     SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:38)
                                                                     #16     ImageProvider.resolve (package:flutter/src/painting/image_provider.dart:264)
                                                                     #17     _ImageProviderResolver.resolve (package:cached_network_image/cached_network_image.dart:190)
                                                                     #18     _CachedNetworkImageState._resolveImage (package:cached_network_image/cached_network_image.dart:276)
                                                                     #19     _CachedNetworkImageState.didChangeDependencies (package:cached_network_image/cached_network_image.dart:258)
                                                                     #20     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3739)
                                                                     #21     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
                                                                     #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
                                                                     #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
                                                                     #24     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4611)
                                                                     #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
                                                                     #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
                                                                     #27     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4611)
                                                                     #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
                                                                     #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
                                                                     #30     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4611)
                                                                     #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
                                                                     #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
                                                                     #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
                                                                     #34     Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
                                                                     #35     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605)
                                                                     #36     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
                                                                     #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
                                                                     #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
                                                                     #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
                                                                     #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
                                                                     #41     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605)
                                                                     #42     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
                                                                     #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
                                                                     #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
                                                                     #45     Com
03-27 18:35:38.556 3414-3429/com.yourcompany.rickandmorty E/flutter: [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
                                                                     'package:flutter/src/painting/image_stream.dart': Failed assertion: line 362: '_codec != null': is not true.
                                                                     #0      _AssertionError._doThrowNew (dart:core-patch/dart:core/errors_patch.dart:37)
                                                                     #1      _AssertionError._throwNew (dart:core-patch/dart:core/errors_patch.dart:33)
                                                                     #2      MultiFrameImageStreamCompleter._handleCodecReady (package:flutter/src/painting/image_stream.dart:362)
                                                                     #3      _RootZone.runUnary (dart:async/zone.dart:1381)
                                                                     #4      _FutureListener.handleValue (dart:async/future_impl.dart:129)
                                                                     #5      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633)
                                                                     #6      _Future._propagateToListeners (dart:async/future_impl.dart:662)
                                                                     #7      _Future._completeError (dart:async/future_impl.dart:485)
                                                                     #8      _SyncCompleter._completeError (dart:async/future_impl.dart:55)
                                                                     #9      _Completer.completeError (dart:async/future_impl.dart:27)
                                                                     #10     CachedNetworkImageProvider._loadAsync (package:cached_network_image/cached_network_image.dart)
                                                                     <asynchronous suspension>
                                                                     #11     CachedNetworkImageProvider.load (package:cached_network_image/cached_network_image.dart:452)
                                                                     #12     ImageProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:266)
                                                                     #13     ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:82)
                                                                     #14     ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:266)
                                                                     #15     SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:38)
                                                                     #16     ImageProvider.resolve (package:flutter/src/painting/image_provider.dart:264)
                                                                     #17     _ImageProviderResolver.resolve (package:cached_network_image/cached_network_image.dart:190)
                                                                     #18     _CachedNetworkImageState._resolveImage (package:cached_network_image/cached_network_image.dart:276)
                                                                     #19     _CachedNetworkImageState.didChangeDependencies (package:cached_network_image/cached_network_image.dart:258)
                                                                     #20     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3739)
                                                                     #21     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
                                                                     #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
                                                                     #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
                                                                     #24     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4611)
                                                                     #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
                                                                     #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
                                                                     #27     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4611)
                                                                     #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
                                                                     #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
                                                                     #30     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4611)
                                                                     #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
                                                                     #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
                                                                     #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
                                                                     #34     Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
                                                                     #35     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605)
                                                                     #36     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
                                                                     #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
                                                                     #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
                                                                     #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
                                                                     #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
                                                                     #41     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605)
                                                                     #42     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
                                                                     #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
                                                                     #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
                                                                     #45     Com
03-27 18:35:45.153 1563-1574/system_process I/ActivityManager: Killing 2469:com.android.messaging/u0a50 (adj 15): empty #17
03-27 18:35:50.245 2234-2242/com.google.android.gms W/SQLiteConnectionPool: A SQLiteConnection object for database '/data/user/0/com.google.android.gms/databases/metrics.db' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.
03-27 18:35:50.247 2234-2242/com.google.android.gms W/SQLiteConnectionPool: A SQLiteConnection object for database '/data/user/0/com.google.android.gms/databases/help_responses.db' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.
03-27 18:35:50.248 2234-2242/com.google.android.gms W/SQLiteConnectionPool: A SQLiteConnection object for database '/data/user/0/com.google.android.gms/databases/auto_complete_suggestions.db' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.
03-27 18:35:55.275 2234-3465/com.google.android.gms D/DropBoxEntryAddedChimeraService: User is not opted-in to Usage & Diagnostics or Lockbox.
03-27 18:36:51.442 3414-3429/com.yourcompany.rickandmorty E/flutter: [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
                                                                     'package:flutter/src/painting/image_stream.dart': Failed assertion: line 362: '_codec != null': is not true.
                                                                     #0      _AssertionError._doThrowNew (dart:core-patch/dart:core/errors_patch.dart:37)
                                                                     #1      _AssertionError._throwNew (dart:core-patch/dart:core/errors_patch.dart:33)
                                                                     #2      MultiFrameImageStreamCompleter._handleCodecReady (package:flutter/src/painting/image_stream.dart:362)
                                                                     #3      _RootZone.runUnary (dart:async/zone.dart:1381)
                                                                     #4      _FutureListener.handleValue (dart:async/future_impl.dart:129)
                                                                     #5      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633)
                                                                     #6      _Future._propagateToListeners (dart:async/future_impl.dart:662)
                                                                     #7      _Future._completeError (dart:async/future_impl.dart:485)
                                                                     #8      _SyncCompleter._completeError (dart:async/future_impl.dart:55)
                                                                     #9      _Completer.completeError (dart:async/future_impl.dart:27)
                                                                     #10     CachedNetworkImageProvider._loadAsync (package:cached_network_image/cached_network_image.dart)
                                                                     <asynchronous suspension>
                                                                     #11     CachedNetworkImageProvider.load (package:cached_network_image/cached_network_image.dart:452)
                                                                     #12     ImageProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:266)
                                                                     #13     ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:82)
                                                                     #14     ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:266)
                                                                     #15     SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:38)
                                                                     #16     ImageProvider.resolve (package:flutter/src/painting/image_provider.dart:264)
                                                                     #17     _ImageProviderResolver.resolve (package:cached_network_image/cached_network_image.dart:190)
                                                                     #18     _CachedNetworkImageState._resolveImage (package:cached_network_image/cached_network_image.dart:276)
                                                                     #19     _CachedNetworkImageState.didChangeDependencies (package:cached_network_image/cached_network_image.dart:258)
                                                                     #20     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3739)
                                                                     #21     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
                                                                     #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
                                                                     #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
                                                                     #24     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4611)
                                                                     #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
                                                                     #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
                                                                     #27     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4611)
                                                                     #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
                                                                     #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
                                                                     #30     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4611)
                                                                     #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
                                                                     #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
                                                                     #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
                                                                     #34     Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
                                                                     #35     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605)
                                                                     #36     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
                                                                     #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
                                                                     #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
                                                                     #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636)
                                                                     #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3478)
                                                                     #41     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605)
                                                                     #42     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600)
                                                                     #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890)
                                                                     #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2693)
                                                                     #45     Com
03-27 18:40:18.764 2749-2819/ng.hotels.app E/FirebaseInstanceId: Token retrieval failed: RST
03-27 18:40:18.799 1866-1866/com.google.android.gms.persistent D/StrictMode: Wrote violation #0 of 5: 13880 bytes
03-27 18:40:18.799 1866-1866/com.google.android.gms.persistent D/StrictMode: Wrote violation #1 of 5: 14400 bytes
03-27 18:40:18.799 1866-1866/com.google.android.gms.persistent D/StrictMode: Wrote violation #2 of 5: 14400 bytes
03-27 18:40:18.799 1866-1866/com.google.android.gms.persistent D/StrictMode: Wrote violation #3 of 5: 14400 bytes
03-27 18:40:18.799 1866-1866/com.google.android.gms.persistent D/StrictMode: Wrote violation #4 of 5: 14400 bytes
03-27 18:40:18.801 2683-2695/com.google.android.gms.unstable D/StrictMode: Wrote violation #0 of 5: 14908 bytes
03-27 18:40:18.801 2683-2695/com.google.android.gms.unstable D/StrictMode: Wrote violation #1 of 5: 15428 bytes
03-27 18:40:18.801 2683-2695/com.google.android.gms.unstable D/StrictMode: Wrote violation #2 of 5: 15428 bytes
03-27 18:40:18.801 2683-2695/com.google.android.gms.unstable D/StrictMode: Wrote violation #3 of 5: 15428 bytes
03-27 18:40:18.801 2683-2695/com.google.android.gms.unstable D/StrictMode: Wrote violation #4 of 5: 15428 bytes
03-27 18:40:18.807 1204-1204/? D/WVCdm: Instantiating CDM.
03-27 18:40:18.808 1204-1645/? I/WVCdm: CdmEngine::OpenSession
03-27 18:40:18.808 1204-1645/? I/WVCdm: Level3 Library Sep 28 2015 13:08:28
03-27 18:40:18.809 1204-1645/? W/WVCdm: Could not read /data/mediadrm/IDM1013/ay64.dat2: No such file or directory
03-27 18:40:18.809 1204-1645/? W/WVCdm: Could not load liboemcrypto.so. Falling back to L3.  dlopen failed: library "liboemcrypto.so" not found
03-27 18:40:18.817 1563-1574/system_process I/AccountManagerService: getTypesVisibleToCaller: isPermitted? true
03-27 18:40:18.817 1204-1645/? I/WVCdm: CdmEngine::QueryKeyControlInfo
03-27 18:40:18.825 1204-1646/? W/WVCdm: BufferReader::Read<T> : Failure during parse: Not enough bytes (4)
03-27 18:40:18.825 1204-1646/? W/WVCdm: CdmEngine::ExtractWidevinePssh: Unable to read atom size.
03-27 18:40:18.825 1204-1646/? I/WVCdm: CdmEngine::GenerateKeyRequest
03-27 18:40:18.825 1204-1646/? D/WVCdm: PrepareKeyRequest: nonce=1345747253
03-27 18:40:18.942 1204-1553/? I/WVCdm: CdmEngine::CloseSession
03-27 18:40:21.341 2694-2694/? W/Binder_1: type=1400 audit(0.0:17): avc: denied { search } for name="1207" dev="proc" ino=1349 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:zygote:s0 tclass=dir permissive=0
03-27 18:40:21.891 2694-2694/? W/Binder_1: type=1400 audit(0.0:18): avc: denied { read } for name="/" dev="tmpfs" ino=3856 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:device:s0 tclass=dir permissive=0
03-27 18:40:24.489 1866-3042/com.google.android.gms.persistent W/GLSUser: [AppCertManager] IOException while requesting key: 
                                                                          java.io.IOException: Invalid device key response.
                                                                              at dxt.a(:com.google.android.gms:267)
                                                                              at dxt.a(:com.google.android.gms:4235)
                                                                              at dxs.a(:com.google.android.gms:47)
                                                                              at dxm.a(:com.google.android.gms:55)
                                                                              at dxl.a(:com.google.android.gms:113)
                                                                              at com.google.android.gms.auth.account.be.legacy.AuthCronChimeraService.b(:com.google.android.gms:3054)
                                                                              at dir.call(:com.google.android.gms:2045)
                                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                              at ixu.run(:com.google.android.gms:453)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                              at jch.run(:com.google.android.gms:17)
                                                                              at java.lang.Thread.run(Thread.java:818)
03-27 18:43:28.984 1563-1580/system_process I/UsageStatsService: User[0] Flushing usage stats to disk
`

**Comment by keluokeda** [comment]
me too.
Syncing files to device iPhone X...
[VERBOSE-2:dart_error.cc(16)] Unhandled exception:
'package:flutter/src/painting/image_stream.dart': Failed assertion: line 362 pos 12: '_codec != null': is not true.
#0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart)
#1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:33:5)
#2      MultiFrameImageStreamCompleter._handleCodecReady (package:flutter/src/painting/image_stream.dart)
#3      _RootZone.runUnary (dart:async/zone.dart:1381:54)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#5      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633:45)
#6      _Future._propagateToListeners (dart:async/future_impl.dart:662:32)
#7      _Future._completeError (dart:async/future_impl.dart:485:5)
#8      _SyncCompleter._completeError (dart:async/future_impl.dart:55:12)
#9      _Completer.completeError (dart:async/future_impl.dart:27:5)
#10     CachedNetworkImageProvider._loadAsync (package:cached_network_image<…>

**Comment by renefloor** [comment]
`_codec != null` is a harmless exception the imageprovider gives when it couldn't load the image, but I'll try to see if I can prevent this exception from showing.
`NoSuchMethodError: The method 'toMap' was called on null.` is a copy of #25

**Comment by KingIdee** [comment]
Okay. Thanks for the quick response. Keep up the good work!

**Comment by volgin** [comment]
I see the same error, but it's not harmless.

I load a list of 75 images. 9 images fail (always the same), while the rest load normally. If I replace `new CachedNetworkImageProvider(_url)` with `new NetworkImage(_url)`, all 75 images load fine. It indicated some problem with caching.

So i tried:
`    CacheManager.maxNrOfCacheObjects = 0;`

Now all 75 images showed up normally.

Then I reset it back:
`    CacheManager.maxNrOfCacheObjects = 200;`

Again, all 75 images loaded correctly. So there is an issue with caching when it goes over the limit. It appears that this `'_codec != null'` assertion error masks another issue.

**Comment by renefloor** [comment]
`'_codec != null'` is only an indication that there was no image to show. 
By default the maxNrOfCacheObjects is 200, so that 75 images should not be a problem. There was some problem with the caching, do you use version `0.0.4` or `0.1.0-rc.1`?
