### ISSUE TITLE
Error: 'ScaledFileImage.load' and 'CachedNetworkImageProvider.load' positional arguments (Fixed!)

### ISSUE THREAD

**Issue by Rofhis** [renefloor/flutter_cached_network_image#266]
Good day,

I started getting this error in my project when I updated Flutter. Error: The method 'ScaledFileImage.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'

**Comment by renefloor** [comment]
Fixed. (See: #261)
I'll leave this open for now for reference.

**Comment by Rofhis** [comment]
Thank you. I didn't see version 2.0.0-rc.

**Comment by renefloor** [comment]
I understand. Pub denies that there is a Flutter 1.10 😅 

![image](https://user-images.githubusercontent.com/15101411/66998045-d68f6c00-f0d3-11e9-8c8e-293a88e31f7b.png)
