### ISSUE TITLE
CachedNetworkImageProvider.load error

### ISSUE THREAD

**Issue by bruceyue** [renefloor/flutter_cached_network_image#268]
The method 'CachedNetworkImageProvider.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.
 
ImageStreamCompleter load(CachedNetworkImageProvider key)
From flutter source, there is two params
ImageStreamCompleter load(T key, DecoderCallback decode);

**Comment by renefloor** [comment]
Please have a look at other issues before posting one.
Duplicate of #266 en #261

**Comment by maAsh-yuppee** [comment]
Just replace cached_network_image: ^1.1.3 to  cached_network_image: ^2.0.0-rc.1
https://pub.dev/packages/cached_network_image/versions/2.0.0-rc.1#-installing-tab-
