### ISSUE TITLE
when i upgrade the sdk of flutter and download the last version of cached network image (^1.1.2+1) 

### ISSUE THREAD

**Issue by mameya007** [renefloor/flutter_cached_network_image#272]
![Annotation 2019-10-18 113222](https://user-images.githubusercontent.com/22181661/67087525-0190c300-f19b-11e9-9e69-9dc164e89a62.png)
any solutions please ?

**Comment by renefloor** [comment]
Please, read the readme and update to 2.0.0-rc

**Comment by apgapg** [comment]
Thanks @renefloor  for the solution. I was getting some unexpected error 'ld normal x86/ framework app not found on ios'. I updated it to 2.0.0 rc version and it worked
