### ISSUE TITLE
How to clear cached local images

### ISSUE THREAD

**Issue by kaina404** [renefloor/flutter_cached_network_image#280]
Hi, How to clear cached local images?

**Comment by renefloor** [comment]
If you add flutter_cache_manager to your dependencies in pubspec you can call `DefaultCacheManager().emptyCache()` to clear all images. For specific files you can call `DefaultCacheManager().removeFile(url)`.

**Comment by P-B1101** [comment]
this option not work anymore in ^2.2.0+1.
any other solution.
