### ISSUE TITLE
When showing a list of network images, on reloading, image shows instantly but on scrolling, image again get loaded everytime

### ISSUE THREAD

**Issue by akhilmorya** [renefloor/flutter_cached_network_image#298]
GestureDetector(
      onDoubleTap: handleLikePost,
      child: Stack(
        alignment: Alignment.center,
        children: <Widget>[
          CachedNetworkImage(
            imageUrl: mediaUrl,
            fit: BoxFit.cover,
            placeholder: (context, url) => Container(
              height: 250,
              child: Center(child: CircularProgressIndicator(),),
            ),
            errorWidget: (context, url, error) => Icon(Icons.error),
          ),
          showHeart ? Animator(
            duration: Duration(milliseconds: 300),
            tween: Tween(
              begin: 0.8,
              end: 1.4),
              curve: Curves.elasticOut,
              cycles: 0,
              builder: (anim) => Transform.scale(
                scale: anim.value,
                child: Icon(
                  Icons.favorite,
                  size: 80.0,
                  color: Colors.white,
                )
              )
            ) : Text(""),
        ],
      )
    );

**Comment by Imgkl** [comment]
I too have this problem!

**Comment by akhilmorya** [comment]
I have the latest version 'cached_network_image: ^1.1.3' still it gives error.

**Comment by joselicht90** [comment]
Same here. It seems is loading every time the image is out of the screen, but i dont know if is loading from cache or url

**Comment by lawonga** [comment]
Same here, any updates?

**Comment by akhilmorya** [comment]
I was finally able to solve it. It was due to large sized images. The images which I was showing was of size around 1-2 mb from firebase storage. I compressed these images to size less than 500kb and it is working properly now.
