### ISSUE TITLE
Adding to flutter project causes `Could not build the application for the simulator.`

### ISSUE THREAD

**Issue by lee-woodridge** [renefloor/flutter_cached_network_image#37]
I have a flutter project which I'm testing. I replaced an `AssetImage` with a `CachedNetworkImageProvider`, as well as including the package, and that results in the failure below:
```
Launching lib/main.dart on iPhone X in debug mode...
Xcode build done
Failed to build iOS app
Error output from Xcode build:
↳
** BUILD FAILED **
Xcode's output:
↳
In file included from /Users/lee/.pub-cache/hosted/pub.dartlang.org/path_provider-0.4.0/ios/Classes/PathProviderPlugin.m:5:
/Users/lee/.pub-cache/hosted/pub.dartlang.org/path_provider-0.4.0/ios/Classes/PathProviderPlugin.h:5:9: fatal error: 'Flutter/Flutter.h' file not found
#import <Flutter/Flutter.h>
^~~~~~~~~~~~~~~~~~~
1 error generated.
In file included from /Users/lee/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.4.1/ios/Classes/SharedPreferencesPlugin.m:5:
/Users/lee/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.4.1/ios/Classes/SharedPreferencesPlugin.h:5:9: fatal error: 'Flutter/Flutter.h' file not found
#import <Flutter/Flutter.h>
^~~~~~~~~~~~~~~~~~~
1 error generated.
Could not build the application for the simulator.
Error launching application on iPhone X.
Exited (sigterm)
```

**Comment by lee-woodridge** [comment]
The difference between getting the error or not is literally just including this package or not. I assume I shouldn't have to import anything else to get it to work?

**Comment by renefloor** [comment]
No you shouldn't have to import anything else. The library itself doesn't have any Android or iOS code, but it does use shared_preferences and path_provider which do have an Android and an iOS part.
These parts of your error output point in the direction of those two libraries:
```
Xcode's output:
/Users/lee/.pub-cache/hosted/pub.dartlang.org/path_provider-0.4.0/ios/Classes/PathProviderPlugin.h:5:9: fatal error: 'Flutter/Flutter.h' file not found
/Users/lee/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.4.1/ios/Classes/SharedPreferencesPlugin.h:5:9: fatal error: 'Flutter/Flutter.h' file not found
```

I was just wondering whether these plugins do work if you directly add them to your project or not.

**Comment by bakatest-me** [comment]
@renefloor when i build on ios 
`Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    Debug.xcconfig line 1: Unable to find included file "Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig"
    Debug.xcconfig line 1: Unable to find included file "Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig"
    /Users/phantomd/@jame/project/flutter/khaopun/ios/Runner/GeneratedPluginRegistrant.m:6:9: fatal error: 'path_provider/PathProviderPlugin.h' file not found
    #import <path_provider/PathProviderPlugin.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
Could not build the application for the simulator.
Error launching application on iPhone X.`

**Comment by bakatest-me** [comment]
@renefloor  sorry i'm fixes by reinstall cocopods 
i think might because my Macos upgrade version from old version
