### ISSUE TITLE
Throws exception when content-type is not image

### ISSUE THREAD

**Issue by FastNinja** [renefloor/flutter_cached_network_image#4]
Hi there,
Great idea - I almost implemented my own cache manager and then found your package.

However I am stuck with the following problem:
 - My images do not always have correct content type. 
 - if content type is not what you expect - the plugin throw exception and does not do anything.

I found the root cause:
```
 if (headers.containsKey("content-type")) {
      var type = headers["content-type"].split("/");
      if (type[0] == "image") {
```

I do not see why would you want to check the `content-type` at all. I would assume that people who pass URL have to make sure it is image....

Would you accept pull request where check `if (type[0] == "image")` is removed?

P.S. image was uploaded to Firebase Storage using Flutter Firebase plugin that autodetects the content type and guesses it wrong 50% of the time.. I will look into fixing that plugin too - but it will require porting native code and also approval from official flutter team later..

Look forward.

**Comment by renefloor** [comment]
Hi FastNinja,

Thanks for your response. When I made this I was already unsure how to make this. For now I made this just for images and expected the http header to give the right extension. There is not really a need to have this only working for images though. What I was not sure about is whether I need to save the file with an extension. I think I can just ignore that all completely and just save the file with a random string as filename. 

If I am correctly the ImageWidget also ignores that and just retrieves the codec from the databytes. I would propose to just remove the whole content-type header check and save the file without an extension. Especially because it is just for caching web data and not really for any user interaction further on. 

What do you think?

**Comment by FastNinja** [comment]
Yes, @renefloor  I took you files, commented out all the lines related to content-type and all images worked!
```
   //if (headers.containsKey("content-type")) {
    // var type = headers["content-type"].split("/");
    // if (type[0] == "image") {
//    if (filePath == null || !filePath.endsWith(type[1])) {
    if (filePath == null) {
      Directory directory = await getTemporaryDirectory();
      var folder = new Directory("${directory.path}/imagecache");
      if (!(await folder.exists())) {
        folder.createSync();
      }
      //var fileName = "${new Uuid().v1()}.${type[1]}";
      var fileName = "${new Uuid().v1()}";
      _map["path"] = "${folder.path}/${fileName}";
    }
    //  }
    // }
```
However...I found that you `NetworkImage` file does not really work with placeholder.
but what people really need - is ability to show placeholder while image is loading.

So I did one extra step - I took another package https://github.com/FaisalAbid/pluto and changed it a bit.
I used their `PlutoImage` file with placeholder and injected your `CachedNetworkImageProvider`. it worked like a charm!

**Comment by renefloor** [comment]
Thanks for testing @FastNinja. 
I was already thinking about removing CachedNetworkImage and only support the ImageProvider as the placeholder is not really core to this package. Did you fork the pluto library or can you directly set an ImageProvider?

I will take the header issue to #5

**Comment by FastNinja** [comment]
@renefloor Pluto did not accept `ImageProvider` in the constructor - so I had to extract Pluto and create new constructor that accepts Image Provider. then I pass your image provider and it all worked...
I am thinking you can take the full Pluto Image concept and just reimplement/steal it..

**Comment by renefloor** [comment]
You could also make a pull request for Pluto that it accepts an imageprovider. Maybe I'll do that myself. Creating your own version of Pluto also means both have to be maintained.
