### ISSUE TITLE
Image didn't change properly

### ISSUE THREAD

**Issue by rickyazhari** [renefloor/flutter_cached_network_image#44]
hi,
I've  two condition issues when image didn't show properly after it show error widget to network image and from network image to error widget 
case : 
   1. parent widget  have  cached_network_image widget  that will change when list widget selected.
   2. list widget have  a collections cached_network_image.

it run smoothly when first list selected is  showing network image from list and so on , but when i select from list  that  showing widget error  there is nothing change at selected widget. it just  show old image before widget error from list selected.

**Comment by renefloor** [comment]
Please re-open if it is still an issue.
