### ISSUE TITLE
Exception cause app crash.

### ISSUE THREAD

**Issue by wendux** [renefloor/flutter_cached_network_image#48]
![image](https://user-images.githubusercontent.com/20411648/40967558-e0fe05e2-68e5-11e8-82a6-7363a57be77d.png)
I have not set breakpoint. When this error  occurred, the IDE highlight this line automatically, then the app  crash.

**Comment by viju85** [comment]
@wendux Did you find a solution to this problem? I am facing the same. When I make a bunch of network calls and of them returns a http error (404), the app crashes with this exception.
