### ISSUE TITLE
Cache Manager - separate concern

### ISSUE THREAD

**Issue by FastNinja** [renefloor/flutter_cached_network_image#5]
Two thoughts crossed my mind:

1. I really couldn't find a place where you eliminate/delete images from cache. it looks like it will grow infinitely. 
2. I actually need similar caching capabilities for other assets- like documents and even maybe JSON data

These leads me to think that your `Cache Manager` actually will be helpful as a separate package.
Caching data on a mobile phone is very common practice/concern so I can see it is much more widely used as `CachedNetworkImageProvider`

Proposal: extract Cache Manager as a separate package. Add ability to eliminate entities. Make it generic so it is not coupled with `HttpHeaders` or any other concerns.

**Comment by renefloor** [comment]
About your points
1) Cleaning the cache is indeed my number 1 priority at the moment, but I was thinking about how best to do that. For now I only used this cachemanager for images that I use all the time and that almost never change. This is also the reason that I didn't yet publish it as a separate package.

2) Like we already discussed in #4 it is very well possible to eliminate the header for content type. I will do that for sure when I publish it separately. About HttpHeaders in general, I will keep the check for 'cache-control', but now I download the file every time when it has no information about that, I can change that to never download again or set that to a default length.

**Comment by FastNinja** [comment]
@renefloor I think my point was nothing to do with header but more to the point that CacheManager sounds like pretty useful package. any data/documents can be cached.
Elimination strategy can be configured or passed as a custom class:

1. for example cache manager can have a size of only 2000 entities and it will remove the most not used one, or the oldest etc..

**Comment by renefloor** [comment]
Yes I understand, I also think it is very useful as a separate package. Using a count is a good idea. I will probably do that in combination with a maximum age. I will make them both configurable by the user, but I think a default of 2000 items is a bit much.

**Comment by renefloor** [comment]
I just made the needed changes in separate feature branch. Would like to hear your opinion.
https://github.com/renefloor/flutter_cached_network_image/tree/feature/generic_cache_manager.
I made one commit for the cleaning of the cache: e1711d0a40e58a56ce7926f226a14186af6117bc
And one to remove the forced check of the image content type: 2d0343cf12ca4d8be724a0e10bfd7990226291a5

**Comment by FastNinja** [comment]
@renefloor looks good, but can be even better. is there a chance you could do Pull Request that will allow me to provide comments etc?

**Comment by renefloor** [comment]
@FastNinja I just moved the cache manager to its own repo and released a first version of it.
https://github.com/renefloor/flutter_cache_manager

Let's move the discussion there. I already refactored some bit and opened an issue for error reporting. I don't have much time coming period, so if you have any breaking issues, please make a pull request for it.
