### ISSUE TITLE
MissingPluginException(No implementation found for method getAll on channel flutter: plugins.flutter.io/shared_preferences)

### ISSUE THREAD

**Issue by ThinkDigitalRepair** [renefloor/flutter_cached_network_image#50]
I'm getting an error when following the official example. I simply replaced my Image.network with CachedNetworkImage, changed the property name, and added a placeholder and this error occurred.
```dart
new CachedNetworkImage(
              imageUrl: 
              "https://www.livekingdomhall.com/public/uploads/congregation_pic/resize_cache/desert-hot-banner_1-210x127.jpg",
              placeholder: CircularProgressIndicator(),
            ),
```
**flutter doctor results:**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.5.5-pre.24, on Mac OS X 10.13.6 17G39b, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0-rc1)
[!] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.4)
[✓] Connected devices (1 available)

flutter: ══╡ EXCEPTION CAUGHT BY SERVICES ╞══════════════════════════════════════════════════════════════════
flutter: The following MissingPluginException was thrown resolving an image codec:
flutter: MissingPluginException(No implementation found for method getAll on channel
flutter: plugins.flutter.io/shared_preferences)
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:278:7)
flutter: <asynchronous suspension>
flutter: #1      SharedPreferences.getInstance (package:shared_preferences/shared_preferences.dart:25:27)
flutter: <asynchronous suspension>
flutter: #2      CacheManager._init (package:flutter_cache_manager/flutter_cache_manager.dart:48:38)
flutter: <asynchronous suspension>
flutter: #3      CacheManager.getInstance.<anonymous closure> (package:flutter_cache_manager/flutter_cache_manager.dart:31:27)
flutter: <asynchronous suspension>
flutter: #4      ReentrantLock._runTask.<anonymous closure>.<anonymous closure> (package:synchronized/src/synchronized_impl.dart:197:29)
flutter: #9      ReentrantLock._runTask.<anonymous closure> (package:synchronized/src/synchronized_impl.dart:195:14)
flutter: #11     ReentrantLock._runTask (package:synchronized/src/synchronized_impl.dart:194:16)
flutter: #12     LockBase._createAndRunTask.run (package:synchronized/src/synchronized_impl.dart:62:14)
flutter: #13     LockBase._createAndRunTask (package:synchronized/src/synchronized_impl.dart:72:17)
flutter: #14     ReentrantLock.synchronized (package:synchronized/src/synchronized_impl.dart:230:12)
flutter: #15     synchronized (package:synchronized/src/synchronized_impl.dart:295:19)
flutter: #16     synchronized (package:synchronized/src/synchronized_compat.dart:35:15)
flutter: #17     CacheManager.getInstance (package:flutter_cache_manager/flutter_cache_manager.dart:28:13)
flutter: <asynchronous suspension>
flutter: #18     CachedNetworkImageProvider._loadAsync (package:cached_network_image/cached_network_image.dart:471:43)
flutter: <asynchronous suspension>
flutter: #19     CachedNetworkImageProvider.load (package:cached_network_image/cached_network_image.dart:462:16)
flutter: #20     ImageProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:266:86)
flutter: #21     ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:143:20)
flutter: #22     ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:266:63)
flutter: #23     SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:38:29)
flutter: #24     ImageProvider.resolve (package:flutter/src/painting/image_provider.dart:264:30)
flutter: #25     _ImageProviderResolver.resolve (package:cached_network_image/cached_network_image.dart:193:29)
flutter: #26     _CachedNetworkImageState._resolveImage (package:cached_network_image/cached_network_image.dart:284:20)
flutter: #27     _CachedNetworkImageState.didChangeDependencies (package:cached_network_image/cached_network_image.dart:261:5)
flutter: #28     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3767:12)
flutter: #29     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
flutter: #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
flutter: #31     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4759:32)
flutter: #32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
flutter: #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
flutter: #34     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
flutter: #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
flutter: #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
flutter: #37     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
flutter: #38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
flutter: #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
flutter: #40     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
flutter: #41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
flutter: #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
flutter: #43     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
flutter: #44     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
flutter: #45     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
flutter: #46     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
flutter: #47     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
flutter: #48     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
flutter: #49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #50     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #51     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
flutter: #52     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
flutter: #53     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
flutter: #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
flutter: #55     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
flutter: #56     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
flutter: #57     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
flutter: #58     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
flutter: #59     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
flutter: #60     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
flutter: #61     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #62     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #63     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
flutter: #64     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
flutter: #65     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
flutter: #66     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
flutter: #67     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
flutter: #68     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #69     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #70     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
flutter: #71     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
flutter: #72     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
flutter: #73     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
flutter: #74     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #75     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #76     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
flutter: #77     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
flutter: #78     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
flutter: #79     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
flutter: #80     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
flutter: #81     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #82     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #83     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
flutter: #84     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
flutter: #85     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
flutter: #86     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
flutter: #87     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
flutter: #88     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4654:14)
flutter: #89     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
flutter: #90     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
flutter: #91     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #92     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #93     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
flutter: #94     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
flutter: #95     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
flutter: #96     Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
flutter: #97     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #98     Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #99     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
flutter: #100    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
flutter: #101    ParentDataElement.mount (package:flutter/src/widgets/framework.dart:3955:11)
flutter: #102    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
flutter: #103    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
flutter: #104    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3653:16)
flutter: #105    Element.rebuild (package:flutter/src/widgets/framework.dart:3495:5)
flutter: #106    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3622:5)
flutter: #107    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3769:11)
flutter: #108    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3617:5)
flutter: #109    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2907:14)
flutter: #110    Element.updateChild (package:flutter/src/widgets/framework.dart:2710:12)
flutter: #111    SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:744:36)
flutter: #112    SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:729:20)
flutter: #113    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2222:19)
flutter: #114    SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:722:11)
flutter: #115    RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:254:23)
flutter: #116    RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1672:58)
flutter: #117    PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:741:15)
flutter: #118    RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1672:13)
flutter: #119    RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:243:5)
flutter: #120    RenderSliverMultiBoxAdaptor.addInitialChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:321:5)
flutter: #121    RenderSliverGrid.performLayout (package:flutter/src/rendering/sliver_grid.dart:543:12)
flutter: #122    RenderObject.layout (package:flutter/src/rendering/object.dart:1576:7)
flutter: #123    RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:182:11)
flutter: #124    RenderObject.layout (package:flutter/src/rendering/object.dart:1576:7)
flutter: #125    RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:405:13)
flutter: #126    RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1311:12)
flutter: #127    RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1229:20)
flutter: #128    RenderObject.layout (package:flutter/src/rendering/object.dart:1576:7)
flutter: #129    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
flutter: #130    RenderObject.layout (package:flutter/src/rendering/object.dart:1576:7)
flutter: #131    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
flutter: #132    RenderObject.layout (package:flutter/src/rendering/object.dart:1576:7)
flutter: #133    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
flutter: #134    RenderObject.layout (package:flutter/src/rendering/object.dart:1576:7)
flutter: #135    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
flutter: #136    RenderObject.layout (package:flutter/src/rendering/object.dart:1576:7)
flutter: #137    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
flutter: #138    RenderObject.layout (package:flutter/src/rendering/object.dart:1576:7)
flutter: #139    MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:141:11)
flutter: #140    _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:399:7)
flutter: #141    MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:211:7)
flutter: #142    RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:355:14)
flutter: #143    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1451:7)
flutter: #144    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:710:18)
flutter: #145    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:270:19)
flutter: #146    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:627:13)
flutter: #147    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
flutter: #148    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
flutter: #149    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
flutter: #150    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
flutter: #151    _invoke (dart:ui/hooks.dart:120:13)
flutter: #152    _drawFrame (dart:ui/hooks.dart:109:3)
flutter: (elided 5 frames from package dart:async)
flutter:
flutter: Image provider:
flutter: CachedNetworkImageProvider("https://www.livekingdomhall.com/public/uploads/congregation_pic/resize_cache/desert-hot-banner_1-210x127.jpg",
flutter: scale: 1.0)
flutter: Image key:
flutter: CachedNetworkImageProvider("https://www.livekingdomhall.com/public/uploads/congregation_pic/resize_cache/desert-hot-banner_1-210x127.jpg",
flutter: scale: 1.0)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by eudangeld** [comment]
Run Flutter clean (or remove your build manually)
if u are on IOS run pod install
Flutter run

**Comment by amatshiye** [comment]
eudangeld Thanks, your solution helped.

**Comment by bijoya-banik** [comment]
nicely works

**Comment by yashj-occipitaltech** [comment]
I am still getting this error ! The above solution is not working for me !

**Comment by hszy00232** [comment]
step1. Run Flutter clean
step2. Run Flutter doctor
step3. Flutter run

**Comment by niypoo** [comment]
same error when try call shared_preferences in backend fetch headless

**Comment by fti-dpogra** [comment]
@eudangeld  
Thanks issue solved!

**Comment by Jagadeesh09-dev** [comment]
I am also still getting this error ! The above solution is not working for me !

**Comment by gianalmada** [comment]
add this line in your main.dart main function : 
SharedPreferences.setMockInitialValues({});

![image](https://user-images.githubusercontent.com/42395245/73902410-5b430780-48c8-11ea-838d-1d6326faf233.png)

**Comment by andersonbrantes** [comment]
I fixed this issue with the @gianalmada above solution.

**Comment by deepakrana0011** [comment]
@Jagadeesh09-dev did you get any solution for this .Because i am getting the same issue with alarm manager

**Comment by lipocodes** [comment]
Help!!!  I implemented the solutions of  gianalmada  & hszy00232   to no avail.

Are you familiar with other solutions?

**Comment by kleber-rr** [comment]
I have had the same problem for days. In my case, the problem is that I am using background_fetch and I need to access preferences during the execution of tasks when the app is closed.

**Comment by YNVoon** [comment]
@kleber-rr are you able to solve it? I am having the same problem as well.

**Comment by renefloor** [comment]
If you are still having problems with SharedPreferences then that is not related to this project, as SharedPreferences is removed from here.

**Comment by DustyLamp** [comment]
@kleber-rr, @YNVoon I'm also having the same issue.

I fixed this issue by simply upgrading shared preferences to the most recent version, but the issue preventing shared preferences from being used still persisted.

I solved it by wrapping my Flutter Application in another class named "Application", registered SharedPreferencesPlugin in "registerWith(PluginRegistry registry)" and setting ".Application" as the application android:name in the AndroidManifest.xml

`    <application
        android:name=".Application"
        android:icon="@mipmap/ic_launcher"
        android:label="RealTracker"
        android:networkSecurityConfig="@xml/network_security_config"
        tools:replace="android:label">`


`import android.util.Log;

import io.flutter.app.FlutterApplication;
import io.flutter.plugin.common.PluginRegistry;
import io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin;

public class Application extends FlutterApplication implements PluginRegistry.PluginRegistrantCallback {

    private static final String TAG = "Application";

    @Override
    public void onCreate(){
        super.onCreate();
        Log.d(TAG, "onCreate: Creating application");
    }

    @Override
    public void registerWith(PluginRegistry registry) {        
        Log.d(TAG, "registerWith: Registering SharedPreferencesPlugin with new registrar at Application level so it can operate in background");
SharedPreferencesPlugin.registerWith(registry.registrarFor("io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin"));

    }
}`

You can do the same thing with other Plugins that you need to use in the background, but keep in mind that you'll have to maintain this yourself rather than have it automatically maintained in the GeneratedPluginRegistrant class

**Comment by renefloor** [comment]
I'm locking this issue as it is not about cached_network_image, but about other plugins.
