### ISSUE TITLE
can use with local image ?

### ISSUE THREAD

**Issue by bakatest-me** [renefloor/flutter_cached_network_image#51]
Ex. new CachedNetworkImageProvider("assets/bg.jpg")

`image: DecorationImage(
            fit: BoxFit.cover,
           image: new CachedNetworkImageProvider(
                "https://images.unsplash.com/photo-1421986527537-888d998adb74?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=21c9e77845e8b2e7ca83e902da4d2f02&auto=format&fit=crop&w=1350&q=80")`

bg with cache from internet
![screen shot 2561-06-30 at 21 55 25](https://user-images.githubusercontent.com/22494087/42126304-4ddfb632-7cb0-11e8-9558-e2ae267aff93.png)

`image: DecorationImage(
            fit: BoxFit.cover,
            image: const AssetImage("assets/bg.jpg"),`

bg image without cache (local file from assets)
![36542450_1926069490778759_4955910720735674368_n](https://user-images.githubusercontent.com/22494087/42126300-300b9e96-7cb0-11e8-9fa7-ec2d3cb09834.png)

Thank you .

**Comment by renefloor** [comment]
@bakatest-me why would you want to do that? AssetImage should be more efficient with that. If AssetImage is really not efficient you should create an issue for the flutter team.
