### ISSUE TITLE
Crashed when I run the demo," _cacheData.containsKey(url) ",_cacheData is null 

### ISSUE THREAD

**Issue by hasonguo** [renefloor/flutter_cached_network_image#52]
The following NoSuchMethodError was thrown resolving an image codec:
flutter: The method 'containsKey' was called on null.
flutter: Receiver: null
flutter: Tried calling: containsKey("http://via.placeholder.com/350x200")
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
flutter: #1      CacheManager.getFile (package:example/flutter_cache_manager.dart:202:21)
flutter: <asynchronous suspension>
flutter: #2      CachedNetworkImageProvider._loadAsync (package:example/cached_network_image.dart:474:35)
flutter: <asynchronous suspension>

code below:

 Future<File> getFile(String url, {Map<String, String> headers}) async {
    String log = "[Flutter Cache Manager] Loading $url";

    if (!_cacheData.containsKey(url)) {
      await _lock.synchronized(() {
        if (!_cacheData.containsKey(url)) {
          _cacheData[url] = new CacheObject(url);
        }
      });
    }

**Comment by renefloor** [comment]
This is fixed now
