### ISSUE TITLE
If image loading error or excetion how to do resolve it

### ISSUE THREAD

**Issue by hasonguo** [renefloor/flutter_cached_network_image#56]
now I  use in this way to solving the exception of image loading.
I  create a  image of “1x1” (widht x height),like below:

 Uint8List _minimumImage = Uint8List.fromList([137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,1,0,0,0,1,8,2,0,0,0,144,119,83,222,0,0,0,1,115,82,71,66,0,174,206,28,233,0,0,0,4,103,65,77,65,0,0,177,143,11,252,97,5,0,0,0,9,112,72,89,115,0,0,14,195,0,0,14,195,1,199,111,168,100,0,0,0,12,73,68,65,84,24,87,99,248,255,255,63,0,5,254,2,254,167,53,129,132,0,0,0,0,73,69,78,68,174,66,96,130]);

But ,I Think This is not the best way to do it.Because sometimes I have a image of “1x1”(widthxheight).
Do you have the best way to do it

**Comment by renefloor** [comment]
@hasonguo what exactly is your question or what are you trying to achieve?
