### ISSUE TITLE
General feedback

### ISSUE THREAD

**Issue by lukepighetti** [renefloor/flutter_cached_network_image#58]
I had high hopes for this package but there are a few things that I am noticing. Perhaps I am doing something wrong.

1) Slower than Image.network()
2) No retry (even 1 retry would be nice!)
3) Changes the look of CircularProgressIndicator
4) Doesn't seem to cache the image any more than Image.network() in practice
5) No way to disable animation to reduce overhead
6) Some images fail to load and don't error
7) If we have an error widget why are we getting exceptions?

**Comment by jonasbark** [comment]
4.) why do you think so? This library provides an offline disk cache that survives app restarts. Image.network does not.

**Comment by lukepighetti** [comment]
When I use it the images don't survive app restarts. Maybe I'm doing something wrong.

**Comment by jonasbark** [comment]
It looks at the header data of the images from the server. If caching isn't activated server-side no file caching will happen.

**Comment by jonasbark** [comment]
Refer to this: https://github.com/renefloor/flutter_cache_manager/blob/master/lib/src/cache_object.dart#L103

**Comment by lukepighetti** [comment]
I just tried advanced_network_image and it loads from file much faster than flutter_cached_network_image and I believe it's because the former runs the animation no matter if the file is cached or not
