### ISSUE TITLE
Sometimes 'FileSystemException: cannot open file, No such file or directory'

### ISSUE THREAD

**Issue by darioielardi** [renefloor/flutter_cached_network_image#67]
In my app, when a user get to the dashboard, some data is fetched from Firebase Firestore, and each document contains an image url, specifically the url obtained uploading an image to Firebase Cloud Storage. 
The image is loaded like:
`    DecorationImage(
       image: CachedNetworkImageProvider(imageUrl),
       fit: BoxFit.cover,
    );
`

The problem is that sometimes the image is loaded correctly without any problem, sometimes an error occurs:
`FileSystemException: Cannot open file, path = '/data/user/0/com.example.myapp/cachecache/919b2e10-9620-11e8-8cce-0beb9308d197.octet-stream' (OS Error: No such file or directory, errno = 2)`

This happens only with images urls uploaded on cloud storage, not with a simple .jpg url.

Did anyone catch this issue?

**Comment by ferdigokdemir** [comment]
+1

**Comment by renefloor** [comment]
Please re-open if it is still an issue.

**Comment by FCMHUB** [comment]
It happens a lot...

**Comment by Pandian-Natarajan** [comment]
@renefloor still facing this issue any fixes or suggestion for this issue ?
