### ISSUE TITLE
Is this still supported?

### ISSUE THREAD

**Issue by BerndWessels** [renefloor/flutter_cached_network_image#70]
Cached Images is such a crucial feature for flutter, but from the issues and PRs comments it seems this is not supported anymore?

Is there an alternative or somebody who would be willing to take this over?

Every time I upgrade my flutter dev channel this breaks and I have to use somebody's fork to keep on going. That is not really acceptable for something so integral and important to flutter as Cached Images should be and makes flutter look unprofessional.

Cached Images should be actually part of the core flutter libraries.

**Comment by pboos** [comment]
It looks like the maintainer is not really doing anything anymore.

It seems like @Cretezy is actually working on this and has many fixed things in his fork. I would vote for @renefloor to take over this project.

@renefloor can you give @Cretezy full access to this repo so he can push, merge, ...? As well please allow @Cretezy to push to the dart hub.

How to do it:
1. Add @Cretezy as collaborator here: https://github.com/renefloor/flutter_cached_network_image/settings/collaboration

2. Add @Cretezy as upload on dart pub:
```pub uploader add charles@cretezy.com``` (guessing the e-mail is right)

3. (optional, or can be done by @Cretezy) Add @Cretezy as author to pubspec.yaml:
```
# Add this below instead of: author: Rene Floor <pub@renefloor.nl>
authors:
- Rene Floor <pub@renefloor.nl>
- Charles Crete <charles@cretezy.com>
```

**Comment by searchy2** [comment]
It's definitely not a good look for Flutter. I'm updating a few projects I've made to Flutter v0.6.0 and Dart 2.0.0 and having libraries stop working and no longer being maintained is VERY troubling. These are projects that were working a month ago!

**Comment by renefloor** [comment]
Sorry guys, I have had a very busy and heavy time last half year so I had to ignore this project. That is all done now so I will maintain this project again from now on. This week I will update all used packages so everything is compatible again. I am also planning to rewrite large parts, for example to use sql to store the cache data. I will carefully look at all pull requests which makes sense to incorporate and which don't. (Also with the rewrite in mind.)

@Cretezy thanks for the offer. It is a good idea to have a second maintainer for when I don't have much time. I will get in contact with you soon.

**Comment by AbdulRahmanAlHamali** [comment]
Thank you @Cretezy and @renefloor for this great effort

If you guys are going to work on anything, please prioritize this issue because it is blocking for many projects.

Thank you again :)
