### ISSUE TITLE
on loaded notification / callback needed

### ISSUE THREAD

**Issue by BerndWessels** [renefloor/flutter_cached_network_image#71]
I often need to know if the image is still loading or has successfully loaded yet.

Can you please add a callback or notification for the loading state.

**Comment by RyanYANG52** [comment]
I added two callback, and tested in my project. Hope that helps 
#97

**Comment by renefloor** [comment]
Now working with the builders

**Comment by RyanYANG52** [comment]
How is the builders going to notify when the image is loaded. Placeholder builder called when start loading, error widget builder called when image loaded failed.

**Comment by renefloor** [comment]
@RyanYANG52 If you set the imageBuilder with a simple Image yourself you also get a callback on loaded.

**Comment by RyanYANG52** [comment]
OK, thanks.

**Comment by kwent** [comment]
@renefloor We need a tutorial or a section in the README cause i doubt most of us know how you do it ...

**Comment by kwent** [comment]
Actually i figure it out. Posting code here for others.

```dart
final VoidCallback onLoaded;
...
CachedNetworkImage(
  imageUrl: "http://via.placeholder.com/200x150",
  imageBuilder: (context, imageProvider) {
    if (onLoaded != null) {
      onLoaded();
    }
    Container(
      decoration: BoxDecoration(
        image: DecorationImage(
            image: imageProvider,
            fit: BoxFit.cover,
            colorFilter: ColorFilter.mode(Colors.red, BlendMode.colorBurn)),
      ),
    );
  },
  placeholder: (context, url) => CircularProgressIndicator(),
  errorWidget: (context, url, error) => Icon(Icons.error),
);
```

**Comment by guenth39** [comment]
This is way too complicated and too much unnecessary code in my opinion. Why do I have to write the complete `imageBuilder` myself just because I want to know when the image is loaded @renefloor ? What's wrong with adding a simple `onLoadedCallback` or at least calling the `progressIndicatorBuilder` again with `progress = 1.0` in every case when the loading is done? 
The answer from @kwent  works but clean and clear code looks different to me.

**Comment by kamleshwebtech** [comment]
> Actually i figure it out. Posting code here for others.
> 
> ```dart
> final VoidCallback onLoaded;
> ...
> CachedNetworkImage(
>   imageUrl: "http://via.placeholder.com/200x150",
>   imageBuilder: (context, imageProvider) {
>     if (onLoaded != null) {
>       onLoaded();
>     }
>     Container(
>       decoration: BoxDecoration(
>         image: DecorationImage(
>             image: imageProvider,
>             fit: BoxFit.cover,
>             colorFilter: ColorFilter.mode(Colors.red, BlendMode.colorBurn)),
>       ),
>     );
>   },
>   placeholder: (context, url) => CircularProgressIndicator(),
>   errorWidget: (context, url, error) => Icon(Icons.error),
> );
> ```

@kwent  What is `onLoaded`? Kindly add a note for the same. Thanks.

**Comment by kamleshwebtech** [comment]
> Actually i figure it out. Posting code here for others.
> 
> ```dart
> final VoidCallback onLoaded;
> ...
> CachedNetworkImage(
>   imageUrl: "http://via.placeholder.com/200x150",
>   imageBuilder: (context, imageProvider) {
>     if (onLoaded != null) {
>       onLoaded();
>     }
>     Container(
>       decoration: BoxDecoration(
>         image: DecorationImage(
>             image: imageProvider,
>             fit: BoxFit.cover,
>             colorFilter: ColorFilter.mode(Colors.red, BlendMode.colorBurn)),
>       ),
>     );
>   },
>   placeholder: (context, url) => CircularProgressIndicator(),
>   errorWidget: (context, url, error) => Icon(Icons.error),
> );
> ```

still getting "CacheManager: Failed to download file from...." error message in VS code console panel.

**Comment by kamleshwebtech** [comment]
> Now working with the builders

Kindly share your implemented solution. I am still searching the solution. Thanks.

**Comment by fareesh** [comment]
You can write something like this - since the imageBuilder is invoked after the image is loaded, if I understand correctly

```dart
imageBuilder: (context, imageProvider) {
  /// Onload code goes here
  return Image(image: imageProvider);
}
```

**Comment by Edijae** [comment]
I agree. there should be fail and success methods just like in other image loading libraries like Glide.

**Comment by DavidOrakpo** [comment]
2023 and the solution given here is still not clear.

**Comment by addalao** [comment]
### My scheme

```markdown
```dart
class CustomNetworkImage extends StatelessWidget {
  final Widget Function(BuildContext, ImageProvider<Object>)? imageBuilder;

  const CustomNetworkImage({
    super.key,
    this.imageBuilder,
    /// some configuration
    /// ....
  });

  @override
  Widget build(BuildContext context) {
    return CachedNetworkImage(
        imageBuilder: imageBuilder,
        /// some configuration
        /// ....
    );
  }
}

class CustomNetworkImageByLoad extends StatefulWidget {
  
  final Function() onLoaded;
  const CustomNetworkImageByLoad({
    super.key,
    required this.onLoaded,
    /// some configuration
    /// ....
  });

  @override
  State<CustomNetworkImageByLoad> createState() =>
      _CustomNetworkImageByLoadState();
}

class _CustomNetworkImageByLoadState extends State<CustomNetworkImageByLoad> {
  /// Whether it has been loaded
  bool _load = false;
  @override
  Widget build(BuildContext context) {
    return CustomNetworkImage(
        imageBuilder: (context, imageProvider) {
            if (!_load) {
                _load = true;
                widget.onLoaded();
            }
            return Image(image: imageProvider);
        },
        /// some configuration
        /// ....
      
    );
  }
}
