### ISSUE TITLE
HTTP Authorization for CachedNetworkImage?

### ISSUE THREAD

**Issue by gregko** [renefloor/flutter_cached_network_image#76]
I have a case where the network resources require authorization, user and password name. It's simple to do if Basic authorization is in use, I can just pass "Authorization" header. However, what if Digest authorization is needed? The first request to the image resource returns 401 (unauthorized) response, one must take all the values from 'www-authenticate' header returned in response and generate correct 'Authorization' header from these values (which may change for each resource request) and re-send...

The server I'm using is not setting any cookie upon successful Digest authorization, so the above dance must be repeated for each resource I request from it.

How could I possibly do this with the methods CachedNetworkImage provides? Or could it be extended to support more secure authorization schemes?

**Comment by renefloor** [comment]
You can now edit the FileFetcher to implement logic like this.
