### ISSUE TITLE
Need a method to clear image cache

### ISSUE THREAD

**Issue by gregko** [renefloor/flutter_cached_network_image#77]
I don't find any way to clear the cache, other than uninstalling, reinstalling the app? Could clear method be provided, for all images, or possibly for groups, e.g. images with the same URL - server part?

**Comment by 9thwall** [comment]
Looking for this +1

**Comment by pablote** [comment]
`Image.network` cache can be cleared using this: https://stackoverflow.com/questions/47209606/how-do-i-clear-flutters-image-cache

It'd be great to have something similar.

**Comment by CatEatFishs** [comment]
how to clear image cache,I not find a method,or tell me the cache directory,i will manual clear cache.

**Comment by renefloor** [comment]
I am working on a new version of the CacheManager. The alpha version on pub is already using that one. As you can see [here](https://github.com/renefloor/flutter_cache_manager/blob/develop/lib/src/cache_manager.dart) that also includes a method to remove a specific url from the cache. It doesn't contain a method yet to clear all.

**Comment by SagarDhiman018** [comment]
> 

Hi all, Any update on this "It doesn't contain a method yet to clear all" ? @renefloor @pablote @9thwall @gregko
