### ISSUE TITLE
Keep images in phone memory (shared preferences)

### ISSUE THREAD

**Issue by bartektartanus** [renefloor/flutter_cached_network_image#86]
Would be nice to have an option to store image in phone memory (eg. shared preferences) and use it when app restarts and there is no internet connection.

Thanks for this great package! :)

**Comment by renefloor** [comment]
@bartektartanus what exactly do you want that the package doesn't provide at this moment? This package stores the file on the phone's storage and should be able to show the image when the phone has no internet connection.

**Comment by renefloor** [comment]
Yes that's the whole idea. The normal networkImage from flutter framework already stores it in memory. This saves the images as files on the cache storage of the phone
