### ISSUE TITLE
Flutter app craching on adding cached_network_image: 0.50 as a dependency

### ISSUE THREAD

**Issue by dopecoder** [renefloor/flutter_cached_network_image#89]
The flutter app has been crashing during launch, when the flutter run command says the application is being installed in the device. I'm not really sure what is causing this issue, but i tried once with the library installed and without. It works perfectly without the library installed.

I tried debugging it more and i found out that the app crashes if cloud_firestore is a dependency with cached_network_image. I'm not really sure why this is happening. I hope someone can help me with this issue!

**Comment by renefloor** [comment]
@dopecoder does version 0.4.2 work fine for you?

**Comment by dopecoder** [comment]
My mistake, I had to add multidex support to my android app which was the root cause for the crashes. Thank you for you time.
