### ISSUE TITLE
Can I set a http proxy for cached_network_image in my app?

### ISSUE THREAD

**Issue by jaggerwang** [renefloor/flutter_cached_network_image#96]
As I know, `cached_network_image` use `http` package in the lower ground, but I can not found how to set proxy for `http`. Is this feature supported?

**Comment by renefloor** [comment]
Not yet, will be supported in a future version.

**Comment by jaggerwang** [comment]
Got it. Waiting for this feature, because my app very need this.

**Comment by renefloor** [comment]
Do you still need this?

**Comment by jaggerwang** [comment]
Not anymore. Thanks!

**Comment by codeknox** [comment]
Hey there, I'm actually searching for a solution to this issue, my app does need to access Internet through a proxy.

Do you want me to open a new issue?

**Comment by renefloor** [comment]
@codeknox you can manipulate the http client of the cache manager. You can see how it is done for firebase here: https://github.com/Baseflow/flutter_cache_manager/tree/develop/flutter_cache_manager_firebase/lib/src

**Comment by mikezander** [comment]
Has anyone solved this? Not sure how to implement the answer @renefloor  is suggesting. Thanks.

**Comment by mikezander** [comment]
@renefloor is this something you'd consider adding support for?

**Comment by nottmey** [comment]
@mikezander I recommend using a global setting for proxy configuration.

I don't know if you considered it, but you can override the default behaviour of any http client with

```dart
    // in your main
    HttpOverrides.global = YourProxyHttpOverrides();
```

```dart
class YourProxyHttpOverrides extends HttpOverrides {
  @override
  HttpClient createHttpClient(SecurityContext? context) {
    final client = super.createHttpClient(context);
    final yourProxyIp = '...'
    final yourProxyPort = '...'
    client.findProxy = (uri) => 'PROXY $yourProxyIp:$yourProxyPort;';
    return client;
  }
}
```
