### ISSUE TITLE
Cached Network Image Provider - Loading Spinner Not Showing

### ISSUE THREAD

**Issue by buddhika-ranasinghe** [renefloor/flutter_cached_network_image#98]
I have tried to use CachedNetworkImage with the flutter carousel pro.
It only accept images array. Since CachedNetworkImage is not a subtype of ImageProvider we have to use 
CachedNetworkImageProvider instead of CachedNetworkImage.

But when I use the CachedNetworkImageProvider, it does not display the loading spinner in the image.

```
new SizedBox(
            height: 170.0,
            // width: 300.0,
            child: new Carousel(
              images: [
                new CachedNetworkImageProvider('https://mycoverpoint.com/wp-content/uploads/Ironman-Facebook-Timeline-Cover-Image.png'),
                new CachedNetworkImageProvider('http://edex.lk/images/content/slider/14693971401413540028logo.jpg'),
                new CachedNetworkImageProvider("http://profilerehab.com/facebook_covers/movies/iron_man_3_cover_2.jpg")
              ],
              showIndicator: false,
              boxFit: BoxFit.fill,
              autoplay: true,
              autoplayDuration: Duration(seconds: 10),
              
            )
          )

```

Please let me know if there is a method we could use the CachedNetworkImageProvider with loading spinner.

**Comment by renefloor** [comment]
Sorry the imageprovider does not provide any such functionality. As far as I know this cannot even be made at the moment.

**Comment by buddhika-ranasinghe** [comment]
@renefloor Thanks for the confirmation. Closing the issue as required information provided.
